export const CHILD_ACTIVITIES = [
  {
    id: "story",
    title: "Inventer la fin de l’histoire",
    category: "Imagination",
    minutes: "10 min",
    idea: "Ouvrez un livre déjà aimé. Avant la dernière page, imaginez ensemble une autre fin. Toutes les idées ont leur place.",
    material: "Un livre illustré",
    icon: "book",
  },
  {
    id: "colors",
    title: "La promenade des couleurs",
    category: "Découverte",
    minutes: "15 min",
    idea: "Lors d’une promenade avec un adulte, cherchez trois couleurs autour de vous. Décrivez ce que vous voyez sans cueillir ni goûter les plantes.",
    material: "Vos yeux curieux",
    icon: "leaf",
  },
  {
    id: "feelings",
    title: "Dessiner la météo du cœur",
    category: "Émotions",
    minutes: "10 min",
    idea: "Soleil, pluie, nuage : chacun dessine comment il se sent aujourd’hui. Écoutez sa réponse sans chercher à la corriger.",
    material: "Papier et crayons adaptés à son âge",
    icon: "sun",
  },
  {
    id: "theatre",
    title: "Le théâtre des doudous",
    category: "Langage",
    minutes: "15 min",
    idea: "Deux doudous se rencontrent. Que se racontent-ils ? Laissez votre enfant choisir les voix, les noms et la suite de leur aventure.",
    material: "Deux peluches",
    icon: "sparkles",
  },
  {
    id: "movement",
    title: "Danser, puis devenir une statue",
    category: "Mouvement",
    minutes: "10 min",
    idea: "Dans un espace dégagé, lancez une chanson. Quand la musique s’arrête, tout le monde devient une statue. Pas de gagnant : le plaisir de bouger ensemble.",
    material: "Une chanson et de la place",
    icon: "music",
  },
  {
    id: "cooking",
    title: "Le goûter des petits chefs",
    category: "Autonomie",
    minutes: "20 min",
    idea: "Confiez une tâche simple : laver un fruit ou mélanger une préparation froide. L’adulte gère les couteaux, la chaleur et les aliments adaptés à l’enfant.",
    material: "Une recette simple, adaptée aux allergies",
    icon: "food",
  },
  {
    id: "memory",
    title: "Un portrait de notre famille",
    category: "Création",
    minutes: "20 min",
    idea: "Dessinez votre famille comme vous la voyez : personnes, animaux, proches. Datez le dessin pour le comparer à celui de l’année prochaine.",
    material: "Une grande feuille et des crayons",
    icon: "palette",
  },
  {
    id: "kindness",
    title: "Le petit merci du jour",
    category: "Lien",
    minutes: "5 min",
    idea: "Chacun raconte un petit moment qu’il a aimé aujourd’hui. Une phrase, un dessin ou un geste suffisent. Les jours difficiles ont aussi leur place.",
    material: "Un moment ensemble",
    icon: "heart",
  },
] as const;
