export interface SizeComparison {
  object: string;
  objectEmoji: string;
  funFact: string;
  babyCanDo: string;
  articleTitle: string;
  articleContent: string;
}

export const sizeComparisons: Record<number, SizeComparison> = {
  1: {
    object: "Grain de sable",
    objectEmoji: "🏖️",
    funFact: "L'œuf fécondé fait la taille d'un grain de sable — plus petit que la pointe d'un crayon !",
    babyCanDo: "Les cellules se divisent à toute vitesse",
    articleTitle: "Les premiers jours après la fécondation",
    articleContent: "Dès la fécondation, le zygote entame un voyage de 6 jours vers l'utérus. Pendant ce trajet, il se divise en 2, puis 4, puis 8 cellules… jusqu'à former un blastocyste d'environ 100 cellules. C'est le tout début de la vie !",
  },
  2: {
    object: "Tête d'épingle",
    objectEmoji: "📌",
    funFact: "L'embryon s'implante dans la paroi utérine — c'est la nidation, un moment crucial !",
    babyCanDo: "S'accroche à la paroi utérine",
    articleTitle: "La nidation : quand bébé s'installe",
    articleContent: "Entre le 6ème et le 10ème jour, le blastocyste s'implante dans l'endomètre. Ce processus peut provoquer de légers saignements (spotting d'implantation). Le placenta commence déjà à se former pour nourrir bébé.",
  },
  3: {
    object: "Graine de moutarde",
    objectEmoji: "🟡",
    funFact: "Le tube neural — futur cerveau et moelle épinière — commence à se former !",
    babyCanDo: "Forme ses 3 couches de cellules fondamentales",
    articleTitle: "L'acide folique : pourquoi c'est essentiel",
    articleContent: "Le tube neural se forme cette semaine. L'acide folique (vitamine B9) est crucial pour sa bonne fermeture. Prenez 400 µg par jour, idéalement depuis avant la conception. On le trouve aussi dans les épinards, brocolis et lentilles.",
  },
  4: {
    object: "Grain de poivre",
    objectEmoji: "🫑",
    funFact: "Le cœur minuscule de bébé commence à battre — environ 110 battements par minute !",
    babyCanDo: "Son cœur bat pour la première fois !",
    articleTitle: "Les premiers battements de cœur",
    articleContent: "À seulement 4 semaines, le cœur primitif de votre bébé commence à battre. Il bat presque deux fois plus vite que le vôtre ! Ce petit cœur pompe déjà du sang à travers les vaisseaux en formation.",
  },
  5: {
    object: "Pépin de pomme",
    objectEmoji: "🍎",
    funFact: "Bébé a maintenant la taille d'un pépin de pomme mais développe déjà ses organes vitaux !",
    babyCanDo: "Développe ses bourgeons de bras et jambes",
    articleTitle: "Gérer les nausées du 1er trimestre",
    articleContent: "Les nausées matinales touchent jusqu'à 80% des femmes enceintes. Quelques astuces : mangez des crackers avant de vous lever, fractionnez vos repas en 5-6 petites portions, buvez du gingembre en infusion, et évitez les odeurs qui vous dérangent.",
  },
  6: {
    object: "Petit pois",
    objectEmoji: "🟢",
    funFact: "Le visage de bébé prend forme : yeux, narines et bouche apparaissent !",
    babyCanDo: "Son cœur a maintenant 4 chambres",
    articleTitle: "Les aliments à éviter pendant la grossesse",
    articleContent: "Certains aliments présentent des risques : fromages au lait cru (listéria), viande crue ou saignante (toxoplasmose), poissons à forte teneur en mercure (thon, espadon). Lavez bien fruits et légumes. En cas de doute, cuisez bien !",
  },
  7: {
    object: "Bonbon Tic Tac",
    objectEmoji: "🍬",
    funFact: "Bébé a la taille d'un Tic Tac et ses doigts commencent à se former !",
    babyCanDo: "Commence à bouger (mais vous ne le sentez pas encore)",
    articleTitle: "Le développement du cerveau",
    articleContent: "Le cerveau de bébé produit environ 250 000 neurones par minute cette semaine ! Les hémisphères droit et gauche se forment. Ce développement incroyable continuera tout au long de la grossesse et bien après la naissance.",
  },
  8: {
    object: "Framboise",
    objectEmoji: "🫐",
    funFact: "Tous les organes principaux sont en place — maintenant ils vont grandir et mûrir !",
    babyCanDo: "Bouge ses bras et ses jambes",
    articleTitle: "La première échographie",
    articleContent: "L'échographie du 1er trimestre (entre 11 et 13 SA) vérifiera le nombre de bébés, la taille (longueur cranio-caudale), le rythme cardiaque, et mesurera la clarté nucale pour le dépistage de la trisomie 21.",
  },
  9: {
    object: "Cerise",
    objectEmoji: "🍒",
    funFact: "Bébé a la taille d'une cerise et commence à avoir des réflexes !",
    babyCanDo: "Peut plier ses bras aux coudes",
    articleTitle: "Le sport pendant la grossesse",
    articleContent: "L'activité physique modérée est recommandée : marche, natation, yoga prénatal, vélo d'appartement. Évitez les sports de contact, les chutes potentielles et les efforts trop intenses. 30 minutes par jour suffisent pour rester en forme.",
  },
  10: {
    object: "Kumquat",
    objectEmoji: "🟠",
    funFact: "Les empreintes digitales de bébé commencent à se former — il sera unique au monde !",
    babyCanDo: "Peut avaler du liquide amniotique",
    articleTitle: "Les changements de votre corps",
    articleContent: "Votre utérus a la taille d'une orange. Vous pouvez remarquer : des veines plus visibles, un léger épaississement de la taille, des gencives sensibles. Votre volume sanguin augmente de 50% pendant la grossesse !",
  },
  11: {
    object: "Clé USB",
    objectEmoji: "💾",
    funFact: "Bébé fait environ 4 cm — la taille d'une clé USB — et ses os commencent à durcir !",
    babyCanDo: "Peut ouvrir et fermer ses poings",
    articleTitle: "Préparer la déclaration de grossesse",
    articleContent: "Pensez à déclarer votre grossesse avant la fin du 3ème mois à l'Assurance Maladie et à la CAF. Cette démarche ouvre vos droits au suivi médical remboursé et au congé maternité. Votre médecin vous donnera le formulaire.",
  },
  12: {
    object: "Citron vert",
    objectEmoji: "🍋",
    funFact: "Bébé peut maintenant bâiller et faire des grimaces !",
    babyCanDo: "Bâille, suce son pouce, grimace",
    articleTitle: "La fin du 1er trimestre en vue !",
    articleContent: "Bonne nouvelle : les nausées diminuent souvent après la semaine 12. Le risque de fausse couche baisse significativement. Beaucoup de parents choisissent ce moment pour annoncer la grossesse à leur entourage.",
  },
  13: {
    object: "Dosette de café",
    objectEmoji: "☕",
    funFact: "Fin du 1er trimestre ! Bébé a maintenant ses cordes vocales — même s'il ne peut pas encore crier !",
    babyCanDo: "A des cordes vocales et des empreintes digitales",
    articleTitle: "Annoncer sa grossesse",
    articleContent: "Le risque de fausse couche a beaucoup diminué. Si vous ne l'avez pas encore fait, c'est souvent le bon moment pour partager la nouvelle ! Annonce en personne, photo échographie, carte grattage… à vous de choisir votre style.",
  },
  14: {
    object: "Kiwi",
    objectEmoji: "🥝",
    funFact: "Bienvenue au 2ème trimestre ! Bébé peut maintenant froncer les sourcils et loucher.",
    babyCanDo: "Produit de l'urine (eh oui !)",
    articleTitle: "Le 2ème trimestre : le plus confortable",
    articleContent: "Le 2ème trimestre est souvent le plus agréable : les nausées s'estompent, l'énergie revient, le ventre n'est pas encore trop gros. Profitez-en pour voyager, faire du shopping bébé, et savourer votre grossesse !",
  },
  15: {
    object: "Balle de golf",
    objectEmoji: "⛳",
    funFact: "Bébé fait des roulades dans votre ventre — un vrai petit gymnaste !",
    babyCanDo: "Peut percevoir la lumière à travers vos parois",
    articleTitle: "Les envies alimentaires",
    articleContent: "Les envies (et dégoûts) alimentaires sont normales. Elles seraient liées aux changements hormonaux. Cédez raisonnablement à vos envies tout en gardant une alimentation équilibrée. Un carré de chocolat ne fera de mal à personne !",
  },
  16: {
    object: "Avocat",
    objectEmoji: "🥑",
    funFact: "Bébé fait la taille d'un avocat et vous pourriez sentir ses premiers mouvements !",
    babyCanDo: "Peut entendre les sons à l'extérieur",
    articleTitle: "Les premiers mouvements de bébé",
    articleContent: "Entre 16 et 22 SA, vous pourriez sentir les premiers mouvements de bébé ! Au début, c'est comme des bulles, des papillons ou des petites vagues. Les mamans qui ont déjà eu un enfant les reconnaissent souvent plus tôt.",
  },
  17: {
    object: "Poire",
    objectEmoji: "🍐",
    funFact: "Le squelette de bébé passe du cartilage à l'os — il se renforce !",
    babyCanDo: "Peut sucer son pouce et faire la moue",
    articleTitle: "Le sommeil pendant la grossesse",
    articleContent: "Dormez sur le côté gauche pour optimiser la circulation sanguine. Un coussin de grossesse peut aider. Évitez de dormir sur le dos à partir du 2ème trimestre. Les insomnies sont normales — essayez la relaxation et la méditation.",
  },
  18: {
    object: "Patate douce",
    objectEmoji: "🍠",
    funFact: "Bébé bâille, a le hoquet et fait des galipettes dans son bain de liquide amniotique !",
    babyCanDo: "Entend votre voix et votre cœur",
    articleTitle: "Parler à son bébé in utero",
    articleContent: "Bébé commence à entendre ! Parlez-lui, chantez, lisez des histoires. Il reconnaîtra votre voix à la naissance. La musique douce a un effet calmant. Le papa peut aussi poser sa bouche contre le ventre pour que bébé l'entende.",
  },
  19: {
    object: "Mangue",
    objectEmoji: "🥭",
    funFact: "Un enduit protecteur (vernix) recouvre la peau de bébé — comme une crème hydratante naturelle !",
    babyCanDo: "Développe ses 5 sens",
    articleTitle: "L'échographie morphologique",
    articleContent: "L'échographie du 2ème trimestre (vers 22 SA) est la plus détaillée. Elle vérifie la morphologie de tous les organes, mesure la croissance, et peut révéler le sexe de bébé (si vous le souhaitez). Prévoyez 30 à 45 minutes.",
  },
  20: {
    object: "Banane",
    objectEmoji: "🍌",
    funFact: "Mi-parcours ! Bébé fait la taille d'une banane et pèse environ 300g.",
    babyCanDo: "Ouvre les yeux pour la première fois",
    articleTitle: "Le mi-parcours de la grossesse",
    articleContent: "Vous êtes à mi-chemin ! Votre ventre est bien visible. C'est le bon moment pour commencer les cours de préparation à l'accouchement, réfléchir à l'aménagement de la chambre, et profiter de cette période souvent sereine.",
  },
  21: {
    object: "Épi de maïs",
    objectEmoji: "🌽",
    funFact: "Bébé fait la taille d'un épi de maïs et goûte ce que vous mangez via le liquide amniotique !",
    babyCanDo: "Goûte les saveurs de votre alimentation",
    articleTitle: "L'alimentation influence les goûts de bébé",
    articleContent: "Le liquide amniotique prend le goût des aliments que vous mangez. Bébé développe déjà ses préférences ! Des études montrent que les bébés exposés à des saveurs variées in utero acceptent plus facilement les aliments solides.",
  },
  22: {
    object: "Boîte à lunch",
    objectEmoji: "🍱",
    funFact: "Les sourcils et les cils de bébé sont formés — il a un vrai visage de bébé !",
    babyCanDo: "Réagit aux sons forts",
    articleTitle: "Choisir sa maternité",
    articleContent: "Inscrivez-vous à la maternité dès le 6ème mois. Critères à considérer : niveau de la maternité (I, II, III), proximité, présence d'une unité néonatale, possibilité d'accouchement physiologique, disponibilité de la péridurale.",
  },
  23: {
    object: "Grosse mangue",
    objectEmoji: "🥭",
    funFact: "Bébé pèse environ 500g — le poids d'un paquet de farine !",
    babyCanDo: "Dort et rêve (mouvements oculaires rapides)",
    articleTitle: "Le test du diabète gestationnel",
    articleContent: "Entre 24 et 28 SA, un test de glycémie (HGPO) sera proposé pour dépister le diabète gestationnel. Il touche 5 à 10% des grossesses. S'il est détecté, un suivi alimentaire et parfois de l'insuline seront mis en place.",
  },
  24: {
    object: "Ballon de handball",
    objectEmoji: "🤾",
    funFact: "Les poumons de bébé commencent à produire du surfactant — essentiel pour respirer à la naissance !",
    babyCanDo: "Ses poumons se préparent pour la respiration",
    articleTitle: "La viabilité : un cap important",
    articleContent: "À 24 SA, bébé atteint le seuil de viabilité. Les poumons commencent à mûrir. En cas de naissance prématurée, les chances de survie augmentent significativement à partir de cette semaine, grâce aux progrès de la néonatalogie.",
  },
  25: {
    object: "Bouteille d'eau (33 cl)",
    objectEmoji: "🧴",
    funFact: "Bébé réagit à votre voix et peut même sursauter si un bruit fort le surprend !",
    babyCanDo: "Explore son visage avec ses mains",
    articleTitle: "La préparation à l'accouchement",
    articleContent: "Plusieurs méthodes existent : classique (sage-femme), sophrologie, haptonomie, hypnose, yoga prénatal, piscine. Testez-en une ou combinez-les. 8 séances sont remboursées par la Sécurité sociale. Commencez vers le 7ème mois.",
  },
  26: {
    object: "Botte de radis",
    objectEmoji: "🥗",
    funFact: "Les yeux de bébé s'ouvrent complètement et il peut voir la lumière qui traverse votre ventre !",
    babyCanDo: "Ouvre et ferme les yeux, cligne",
    articleTitle: "Préparer la chambre de bébé",
    articleContent: "Commencez à aménager ! L'essentiel : un lit conforme aux normes (barreaux espacés de 4,5 à 6,5 cm), un matelas ferme, pas de tour de lit ni coussin. Peignez 2 mois avant l'arrivée pour que les COV s'évaporent. Température idéale : 19°C.",
  },
  27: {
    object: "Chou-fleur",
    objectEmoji: "🥦",
    funFact: "Fin du 2ème trimestre ! Bébé pèse presque 1 kg et mesure 35 cm environ.",
    babyCanDo: "A des cycles réguliers de sommeil et d'éveil",
    articleTitle: "Le 3ème trimestre approche",
    articleContent: "Dernière ligne droite ! Les prochaines semaines, bébé va surtout prendre du poids et ses poumons vont mûrir. Vous pourriez ressentir des contractions de Braxton-Hicks (fausses contractions) — c'est normal, votre corps se prépare.",
  },
  28: {
    object: "Aubergine",
    objectEmoji: "🍆",
    funFact: "3ème trimestre ! Le cerveau de bébé développe des milliards de neurones chaque jour.",
    babyCanDo: "Rêve pendant son sommeil",
    articleTitle: "Le congé maternité",
    articleContent: "En France : 6 semaines avant et 10 semaines après (1er/2ème enfant). 8+18 semaines à partir du 3ème. Jumeaux : 12+22 semaines. Pensez à informer votre employeur et la CPAM. Le congé pathologique peut ajouter 2 semaines avant.",
  },
  29: {
    object: "Courge butternut",
    objectEmoji: "🎃",
    funFact: "Bébé cligne des yeux, tousse, a le hoquet et fait pipi — un vrai petit être humain !",
    babyCanDo: "Différencie les voix familières",
    articleTitle: "Les contractions de Braxton-Hicks",
    articleContent: "Ces contractions d'entraînement sont normales dès le 3ème trimestre. Le ventre durcit puis se relâche, sans douleur intense. Contrairement au vrai travail, elles sont irrégulières et cessent au repos. Consultez si elles deviennent régulières.",
  },
  30: {
    object: "Gros chou",
    objectEmoji: "🥬",
    funFact: "Le cerveau de bébé commence à se plisser — ces sillons augmentent la surface cérébrale !",
    babyCanDo: "Peut tourner la tête vers une source de lumière",
    articleTitle: "La valise de maternité",
    articleContent: "Pour maman : chemises de nuit ouvertes devant, brumisateur, chaussettes, serviettes hygiéniques post-partum. Pour bébé : bodies, pyjamas (taille naissance + 1 mois), bonnet, chaussettes, couverture. N'oubliez pas le carnet de santé et les papiers !",
  },
  31: {
    object: "Noix de coco",
    objectEmoji: "🥥",
    funFact: "Bébé pèse environ 1,5 kg et peut déjà reconnaître les berceuses que vous lui chantez !",
    babyCanDo: "Reconnaît la musique et les voix familières",
    articleTitle: "Le projet de naissance",
    articleContent: "Rédigez vos souhaits pour l'accouchement : position, péridurale, musique, peau à peau, allaitement… Ce n'est pas un contrat mais un outil de dialogue avec l'équipe médicale. Restez flexible — l'important est la sécurité de tous.",
  },
  32: {
    object: "Ananas",
    objectEmoji: "🍍",
    funFact: "Bébé prend environ 200g par semaine maintenant — il se remplit de jolies rondeurs !",
    babyCanDo: "Pratique la respiration (inspire/expire du liquide)",
    articleTitle: "L'échographie du 3ème trimestre",
    articleContent: "Cette échographie vérifie la croissance, la position de bébé (tête en bas ?), la quantité de liquide amniotique et la position du placenta. Si bébé est en siège, des techniques de version peuvent être proposées.",
  },
  33: {
    object: "Ballon de foot ⚽",
    objectEmoji: "⚽",
    funFact: "Les os de bébé durcissent, sauf le crâne qui reste souple pour l'accouchement !",
    babyCanDo: "Distingue la lumière de l'obscurité",
    articleTitle: "Les positions de bébé",
    articleContent: "La position idéale est tête en bas (céphalique). Si bébé est en siège, ne paniquez pas : il peut encore se retourner jusqu'à 36 SA. Des exercices (position à quatre pattes) et la version par manœuvre externe peuvent aider.",
  },
  34: {
    object: "Melon cantaloup",
    objectEmoji: "🍈",
    funFact: "Les poumons de bébé sont presque matures — s'il naissait maintenant, il aurait d'excellentes chances !",
    babyCanDo: "Ses ongles atteignent le bout de ses doigts",
    articleTitle: "Préparer la valise de maternité",
    articleContent: "C'est le moment ! Préparez deux sacs : un pour la salle d'accouchement (documents, tenue bébé, brumisateur) et un pour le séjour (vêtements maman/bébé, produits d'hygiène, coussin d'allaitement). Gardez la liste dans MamaTrack !",
  },
  35: {
    object: "Gros melon",
    objectEmoji: "🍈",
    funFact: "Bébé grossit de 200 à 250g par semaine — il fait ses réserves de graisse pour l'extérieur !",
    babyCanDo: "A des cycles d'éveil et sommeil bien définis",
    articleTitle: "Les signes du travail",
    articleContent: "Les vrais signes : contractions régulières et de plus en plus rapprochées, perte du bouchon muqueux (glaire teintée), rupture de la poche des eaux. Allez à la maternité quand les contractions durent 1 min, toutes les 5 min, depuis 1h.",
  },
  36: {
    object: "Laitue romaine",
    objectEmoji: "🥬",
    funFact: "Bébé descend dans le bassin — votre ventre 'tombe' et vous respirez mieux !",
    babyCanDo: "Se positionne tête en bas pour la naissance",
    articleTitle: "La descente de bébé",
    articleContent: "Bébé s'engage dans le bassin. Vous pouvez ressentir une pression pelvienne, des envies fréquentes d'uriner et une meilleure respiration. C'est bon signe ! La tête de bébé appuie sur le col, ce qui aidera à la dilatation.",
  },
  37: {
    object: "Pastèque mini",
    objectEmoji: "🍉",
    funFact: "Bébé est considéré 'à terme' ! Il pourrait naître à tout moment en bonne santé.",
    babyCanDo: "Sait téter, déglutir et respirer de façon coordonnée",
    articleTitle: "Bébé est à terme !",
    articleContent: "À 37 SA, bébé est officiellement à terme. Ses poumons sont matures, il régule sa température. Restez attentive aux contractions. Le bouchon muqueux peut se détacher. Finalisez vos préparatifs : valise, trajet maternité, garde pour les aînés.",
  },
  38: {
    object: "Citrouille moyenne",
    objectEmoji: "🎃",
    funFact: "Le méconium (premier caca de bébé) s'accumule dans ses intestins — surprise à la naissance !",
    babyCanDo: "A une prise ferme — il peut serrer votre doigt",
    articleTitle: "Les derniers préparatifs",
    articleContent: "Vérifiez : siège auto installé, chambre prête, valise bouclée, numéro de la maternité enregistré, trajet repéré. Préparez aussi des repas à congeler pour le retour ! Profitez de ces derniers moments à deux (ou en famille).",
  },
  39: {
    object: "Pastèque",
    objectEmoji: "🍉",
    funFact: "Bébé pèse en moyenne 3,3 kg et mesure 50 cm — prêt pour le grand jour !",
    babyCanDo: "Est totalement prêt pour la vie à l'extérieur",
    articleTitle: "Reconnaître le vrai travail",
    articleContent: "Le vrai travail se distingue par des contractions régulières, de plus en plus intenses et rapprochées, qui ne cessent pas au repos. Chronométrez-les avec MamaTrack ! Direction la maternité : 1 contraction/5 min pendant 1h (ou rupture des eaux).",
  },
  40: {
    object: "Grosse citrouille",
    objectEmoji: "🎃",
    funFact: "Jour J ! Seulement 4% des bébés naissent exactement à leur date prévue.",
    babyCanDo: "Prêt à pousser son premier cri !",
    articleTitle: "Le jour de l'accouchement",
    articleContent: "Le jour J est là (ou presque) ! Rappelez-vous : chaque accouchement est unique. Faites confiance à votre corps et à votre équipe médicale. Le peau à peau immédiat est recommandé. Bébé vous reconnaîtra dès la première seconde.",
  },
  41: {
    object: "Pastèque XL",
    objectEmoji: "🍉",
    funFact: "Pas de panique ! 30% des grossesses dépassent le terme. Bébé choisit son moment.",
    babyCanDo: "Continue de grandir et de prendre du poids",
    articleTitle: "Dépassement de terme",
    articleContent: "Votre médecin ou sage-femme vous surveillera de près : monitoring, échographie, quantité de liquide amniotique. Un déclenchement sera probablement proposé autour de 41+5 SA. Marchez, bougez — ça peut aider bébé à se décider !",
  },
  42: {
    object: "Pastèque géante",
    objectEmoji: "🍉",
    funFact: "Le plus gros bébé jamais né pesait 10,2 kg en 1955 en Italie — rassurez-vous, le vôtre sera normal !",
    babyCanDo: "Est absolument prêt — c'est le moment !",
    articleTitle: "Le déclenchement de l'accouchement",
    articleContent: "Si bébé n'est toujours pas là, un déclenchement sera programmé. Plusieurs méthodes existent : tampon de prostaglandines, perfusion d'ocytocine, rupture artificielle des membranes. C'est une décision médicale pour la sécurité de tous.",
  },
};

export function getSizeComparison(week: number): SizeComparison | undefined {
  return sizeComparisons[week];
}
