export interface WeekData {
  week: number;
  sizeMm: number;
  weightG: number;
  fruit: string;
  fruitEmoji: string;
  babyDevelopment: string;
  momTips: string;
  trimester: 1 | 2 | 3;
}

export const pregnancyData: WeekData[] = [
  {
    week: 1,
    sizeMm: 0,
    weightG: 0,
    fruit: "Graine de pavot",
    fruitEmoji: "🌱",
    babyDevelopment: "La fécondation vient d'avoir lieu. L'œuf fécondé, appelé zygote, commence son voyage vers l'utérus. La division cellulaire a commencé.",
    momTips: "Commencez à prendre de l'acide folique si ce n'est pas déjà fait. Évitez l'alcool et la caféine.",
    trimester: 1,
  },
  {
    week: 2,
    sizeMm: 0.1,
    weightG: 0,
    fruit: "Graine de sésame",
    fruitEmoji: "🫘",
    babyDevelopment: "L'embryon s'implante dans la paroi utérine. Le blastocyste se développe et les premières cellules spécialisées apparaissent.",
    momTips: "Continuez l'acide folique. Consultez votre médecin pour confirmer la grossesse.",
    trimester: 1,
  },
  {
    week: 3,
    sizeMm: 0.5,
    weightG: 0,
    fruit: "Graine de chia",
    fruitEmoji: "🌰",
    babyDevelopment: "Les trois couches germinales se forment : l'ectoderme, le mésoderme et l'endoderme. Le système nerveux commence à se former.",
    momTips: "Vous pourriez ressentir les premiers signes de grossesse : fatigue, nausées légères. Reposez-vous.",
    trimester: 1,
  },
  {
    week: 4,
    sizeMm: 1,
    weightG: 0,
    fruit: "Grain de riz",
    fruitEmoji: "🍚",
    babyDevelopment: "Le tube neural se forme, précurseur du cerveau et de la moelle épinière. Le cœur primitif commence à battre.",
    momTips: "Testez votre grossesse à la maison. Prenez rendez-vous chez votre gynécologue.",
    trimester: 1,
  },
  {
    week: 5,
    sizeMm: 4,
    weightG: 0,
    fruit: "Graine de sésame",
    fruitEmoji: "🫘",
    babyDevelopment: "Le cœur bat pour la première fois ! Les bourgeons des membres apparaissent. Le cerveau, les yeux et les oreilles commencent à se former.",
    momTips: "Les nausées matinales peuvent commencer. Mangez de petits repas fréquents et restez hydratée.",
    trimester: 1,
  },
  {
    week: 6,
    sizeMm: 8,
    weightG: 0,
    fruit: "Lentille",
    fruitEmoji: "🟢",
    babyDevelopment: "Le visage prend forme avec les yeux, les narines et la bouche. Les bras et les jambes s'allongent. Le cœur a maintenant 4 chambres.",
    momTips: "Évitez les odeurs fortes si elles causent des nausées. Le gingembre peut aider à soulager les nausées.",
    trimester: 1,
  },
  {
    week: 7,
    sizeMm: 13,
    weightG: 0,
    fruit: "Myrtille",
    fruitEmoji: "🫐",
    babyDevelopment: "Le cerveau se développe rapidement. Les doigts et les orteils commencent à apparaître. Le foie produit les globules rouges.",
    momTips: "Votre utérus a doublé de taille. Vous pourriez ressentir des ballonnements. Portez des vêtements confortables.",
    trimester: 1,
  },
  {
    week: 8,
    sizeMm: 16,
    weightG: 1,
    fruit: "Framboise",
    fruitEmoji: "🍓",
    babyDevelopment: "Tous les organes vitaux sont en place. Le bébé peut faire de petits mouvements. Les paupières se forment.",
    momTips: "Première échographie possible. Parlez à votre médecin de vos médicaments habituels.",
    trimester: 1,
  },
  {
    week: 9,
    sizeMm: 23,
    weightG: 2,
    fruit: "Cerise",
    fruitEmoji: "🍒",
    babyDevelopment: "Le bébé ressemble maintenant à un petit humain. Les muscles faciaux se développent. Les dents commencent à se former sous les gencives.",
    momTips: "La fatigue est normale au premier trimestre. Dormez autant que possible et acceptez l'aide de vos proches.",
    trimester: 1,
  },
  {
    week: 10,
    sizeMm: 31,
    weightG: 4,
    fruit: "Fraise",
    fruitEmoji: "🍓",
    babyDevelopment: "Le stade embryonnaire est terminé, bébé est maintenant un fœtus. Les ongles commencent à pousser. Il peut avaler et donner des coups.",
    momTips: "Les nausées devraient commencer à diminuer bientôt. Commencez à penser à vos vêtements de maternité.",
    trimester: 1,
  },
  {
    week: 11,
    sizeMm: 41,
    weightG: 7,
    fruit: "Figue",
    fruitEmoji: "🟤",
    babyDevelopment: "Le bébé peut ouvrir et fermer les poings. Les os commencent à se durcir. Le diaphragme se développe (préparation au hoquet).",
    momTips: "Vous pouvez commencer à informer votre entourage de votre grossesse. Commencez des exercices prénataux doux.",
    trimester: 1,
  },
  {
    week: 12,
    sizeMm: 53,
    weightG: 14,
    fruit: "Citron vert",
    fruitEmoji: "🍋",
    babyDevelopment: "Les réflexes se développent. Le bébé peut sucer son pouce. Les organes génitaux sont visibles à l'échographie.",
    momTips: "Fin du premier trimestre ! Le risque de fausse couche diminue significativement. Première échographie du 1er trimestre.",
    trimester: 1,
  },
  {
    week: 13,
    sizeMm: 74,
    weightG: 23,
    fruit: "Pea pod",
    fruitEmoji: "🫛",
    babyDevelopment: "Les empreintes digitales se forment. Le bébé peut faire des grimaces. Les intestins se déplacent dans le corps.",
    momTips: "Bienvenue au 2ème trimestre ! L'énergie revient généralement. Commencez à penser à la chambre de bébé.",
    trimester: 2,
  },
  {
    week: 14,
    sizeMm: 87,
    weightG: 43,
    fruit: "Citron",
    fruitEmoji: "🍋",
    babyDevelopment: "Le bébé peut faire la moue et froncer les sourcils. Les reins fonctionnent et produisent de l'urine. Les cheveux commencent à pousser.",
    momTips: "Vous commencez à vous sentir mieux. C'est le bon moment pour faire de l'exercice prénatal doux.",
    trimester: 2,
  },
  {
    week: 15,
    sizeMm: 101,
    weightG: 70,
    fruit: "Pomme",
    fruitEmoji: "🍎",
    babyDevelopment: "Le bébé peut entendre les sons. Il bouge beaucoup même si vous ne le sentez pas encore. Les os continuent de se durcir.",
    momTips: "Parlez, chantez à votre bébé - il commence à entendre ! Commencez à planifier votre congé maternité.",
    trimester: 2,
  },
  {
    week: 16,
    sizeMm: 116,
    weightG: 100,
    fruit: "Avocat",
    fruitEmoji: "🥑",
    babyDevelopment: "Les yeux peuvent faire de petits mouvements. Le bébé peut tenir sa tête droite. Le système circulatoire fonctionne pleinement.",
    momTips: "Vous pourriez sentir les premiers mouvements de bébé (quickening). Commencez les exercices de Kegel.",
    trimester: 2,
  },
  {
    week: 17,
    sizeMm: 130,
    weightG: 140,
    fruit: "Poire",
    fruitEmoji: "🍐",
    babyDevelopment: "La graisse commence à se former sous la peau. Le bébé développe ses propres empreintes digitales uniques. Il peut avoir le hoquet.",
    momTips: "Dormez sur le côté gauche pour améliorer la circulation. Utilisez un coussin de maternité.",
    trimester: 2,
  },
  {
    week: 18,
    sizeMm: 142,
    weightG: 190,
    fruit: "Poivron",
    fruitEmoji: "🫑",
    babyDevelopment: "Le bébé est très actif. Les nerfs sont enrobés de myéline. Il peut entendre votre voix et les sons extérieurs clairement.",
    momTips: "Deuxième échographie morphologique bientôt. Vous pourriez découvrir le sexe de bébé si vous le souhaitez.",
    trimester: 2,
  },
  {
    week: 19,
    sizeMm: 152,
    weightG: 240,
    fruit: "Mangue",
    fruitEmoji: "🥭",
    babyDevelopment: "Le vernix caseosa (substance blanchâtre protectrice) recouvre la peau. Les sens continuent de se développer. Bébé avale du liquide amniotique.",
    momTips: "Commencez à hydrater votre ventre pour éviter les vergetures. Portez un soutien-gorge adapté.",
    trimester: 2,
  },
  {
    week: 20,
    sizeMm: 160,
    weightG: 300,
    fruit: "Banane",
    fruitEmoji: "🍌",
    babyDevelopment: "Mi-chemin ! Bébé dort et se réveille selon un rythme régulier. Les sourcils et les cils sont présents. Le vernix protège la peau.",
    momTips: "Félicitations - vous êtes à mi-parcours ! Échographie morphologique du 2ème trimestre. Commencez les cours de préparation à l'accouchement.",
    trimester: 2,
  },
  {
    week: 21,
    sizeMm: 267,
    weightG: 360,
    fruit: "Carotte",
    fruitEmoji: "🥕",
    babyDevelopment: "Le bébé peut sentir les saveurs du liquide amniotique. Il peut maintenant se retourner. Les mouvements sont plus coordonnés.",
    momTips: "Vos mouvements de bébé sont maintenant réguliers. Notez-les si vous ne les sentez pas pendant 2h.",
    trimester: 2,
  },
  {
    week: 22,
    sizeMm: 278,
    weightG: 430,
    fruit: "Maïs",
    fruitEmoji: "🌽",
    babyDevelopment: "Les yeux sont complètement formés mais encore fermés. Le bébé peut saisir le cordon ombilical. Les oreilles fonctionnent bien.",
    momTips: "Pensez à la liste de naissance. Visitez la maternité. Discutez du plan de naissance avec votre sage-femme.",
    trimester: 2,
  },
  {
    week: 23,
    sizeMm: 288,
    weightG: 501,
    fruit: "Pamplemousse",
    fruitEmoji: "🍊",
    babyDevelopment: "Le bébé passe 500g ! Les poumons se développent (production de surfactant). Il peut maintenant survivre en dehors de l'utérus avec aide médicale.",
    momTips: "Surveillez les gonflements des pieds et mains. Continuez les exercices doux. Hydratez-vous bien.",
    trimester: 2,
  },
  {
    week: 24,
    sizeMm: 298,
    weightG: 600,
    fruit: "Épi de maïs",
    fruitEmoji: "🌽",
    babyDevelopment: "Les poumons se développent rapidement. Le bébé réagit aux sons forts. Il est maintenant viable (seuil de viabilité légal).",
    momTips: "Test de diabète gestationnel (entre 24-28 semaines). Continuez à surveiller les mouvements de bébé.",
    trimester: 2,
  },
  {
    week: 25,
    sizeMm: 347,
    weightG: 660,
    fruit: "Rutabaga",
    fruitEmoji: "🟣",
    babyDevelopment: "Les mains sont pleinement développées. Le bébé répond à la lumière. Sa peau devient moins translucide.",
    momTips: "Commencez à penser à l'allaitement. Consultez une consultante en lactation si nécessaire.",
    trimester: 2,
  },
  {
    week: 26,
    sizeMm: 360,
    weightG: 760,
    fruit: "Laitue romaine",
    fruitEmoji: "🥬",
    babyDevelopment: "Les yeux s'ouvrent pour la première fois. Le bébé peut cligner des yeux. Le cerveau connaît une croissance rapide.",
    momTips: "Reposez-vous quand vous pouvez. Les crampes nocturnes sont fréquentes - étirez vos mollets avant de dormir.",
    trimester: 2,
  },
  {
    week: 27,
    sizeMm: 370,
    weightG: 875,
    fruit: "Chou-fleur",
    fruitEmoji: "🥦",
    babyDevelopment: "Le cerveau continue de se développer rapidement. Le bébé peut reconnaître votre voix. Les cycles de sommeil/éveil sont établis.",
    momTips: "Dernier mois du 2ème trimestre. Préparez votre valise de maternité (vous avez encore le temps !)",
    trimester: 2,
  },
  {
    week: 28,
    sizeMm: 380,
    weightG: 1005,
    fruit: "Aubergine",
    fruitEmoji: "🍆",
    babyDevelopment: "Le bébé peut rêver (phase REM). Les poumons sont presque matures. La peau se lisse grâce à la graisse sous-cutanée.",
    momTips: "Bienvenue au 3ème trimestre ! Troisième échographie prévue. Commencez à compter les mouvements quotidiennement.",
    trimester: 3,
  },
  {
    week: 29,
    sizeMm: 390,
    weightG: 1150,
    fruit: "Butternut",
    fruitEmoji: "🎃",
    babyDevelopment: "Le bébé accumule de la graisse. Les muscles et les poumons mûrissent. Il peut saisir solidement si quelque chose touche sa main.",
    momTips: "Vous pourriez avoir du mal à dormir. Utilisez des coussins pour trouver une position confortable.",
    trimester: 3,
  },
  {
    week: 30,
    sizeMm: 400,
    weightG: 1300,
    fruit: "Chou",
    fruitEmoji: "🥬",
    babyDevelopment: "Le bébé produit des globules rouges. Son cerveau grandit vite avec des circonvolutions. Il a maintenant les yeux ouverts quand il est éveillé.",
    momTips: "Le souffle court est fréquent car bébé appuie sur votre diaphragme. Prenez des pauses régulières.",
    trimester: 3,
  },
  {
    week: 31,
    sizeMm: 410,
    weightG: 1500,
    fruit: "Noix de coco",
    fruitEmoji: "🥥",
    babyDevelopment: "Les reins fonctionnent pleinement. Le bébé peut tourner la tête. Ses pupilles réagissent à la lumière et à l'obscurité.",
    momTips: "Réfléchissez à votre plan de naissance. Visitez la maternité si ce n'est pas encore fait.",
    trimester: 3,
  },
  {
    week: 32,
    sizeMm: 420,
    weightG: 1700,
    fruit: "Jicama",
    fruitEmoji: "⚪",
    babyDevelopment: "Le bébé pratique la respiration. Ses ongles et cheveux continuent de pousser. Il se positionne souvent tête en bas.",
    momTips: "Les contractions de Braxton-Hicks peuvent commencer. Ce sont des contractions d'entraînement, normales.",
    trimester: 3,
  },
  {
    week: 33,
    sizeMm: 430,
    weightG: 1900,
    fruit: "Ananas",
    fruitEmoji: "🍍",
    babyDevelopment: "Le crâne reste souple pour faciliter l'accouchement. Le bébé coordonne respiration, succion et déglutition.",
    momTips: "Commencez à préparer votre valise de maternité si ce n'est pas encore fait. Notez les contractions.",
    trimester: 3,
  },
  {
    week: 34,
    sizeMm: 450,
    weightG: 2100,
    fruit: "Melon cantaloup",
    fruitEmoji: "🍈",
    babyDevelopment: "Le système nerveux central est presque mature. Le bébé reconnaît les voix familières. Sa peau est de moins en moins ridée.",
    momTips: "Consultez votre sage-femme plus fréquemment. Apprenez les signes du travail prématuré.",
    trimester: 3,
  },
  {
    week: 35,
    sizeMm: 460,
    weightG: 2400,
    fruit: "Melon de miel",
    fruitEmoji: "🍈",
    babyDevelopment: "Les reins sont pleinement développés. La plupart des bébés nés à 35 semaines se portent bien. La graisse sous-cutanée continue de s'accumuler.",
    momTips: "Reposez-vous le plus possible. La fatigue est normale. Préparez-vous mentalement pour l'accouchement.",
    trimester: 3,
  },
  {
    week: 36,
    sizeMm: 470,
    weightG: 2600,
    fruit: "Papaye",
    fruitEmoji: "🥭",
    babyDevelopment: "Le bébé est considéré comme prématuré tardif. Il a la taille d'une papaye. Les poumons sont presque totalement matures.",
    momTips: "Votre ventre peut descendre (engagement). La pression sur le diaphragme diminue mais sur la vessie augmente.",
    trimester: 3,
  },
  {
    week: 37,
    sizeMm: 480,
    weightG: 2900,
    fruit: "Chou frisé",
    fruitEmoji: "🥬",
    babyDevelopment: "Le bébé est considéré à terme précoce. Ses poumons sont matures. Il continue de prendre du poids.",
    momTips: "Le bébé peut naître à tout moment maintenant. Finalisez votre valise. Connaissez les signes du travail.",
    trimester: 3,
  },
  {
    week: 38,
    sizeMm: 490,
    weightG: 3100,
    fruit: "Poireau",
    fruitEmoji: "🧅",
    babyDevelopment: "Le bébé est à terme. Il a perdu la plupart du vernix. Ses organes sont pleinement fonctionnels.",
    momTips: "La date d'accouchement approche ! Restez active avec des promenades douces. Reposez-vous quand possible.",
    trimester: 3,
  },
  {
    week: 39,
    sizeMm: 500,
    weightG: 3300,
    fruit: "Pastèque mini",
    fruitEmoji: "🍉",
    babyDevelopment: "Le bébé est pleinement à terme. Il continue de prendre du poids. Son cerveau continue de se développer même après la naissance.",
    momTips: "Chaque jour compte pour la maturation du cerveau. Soyez attentive aux contractions régulières et à la perte des eaux.",
    trimester: 3,
  },
  {
    week: 40,
    sizeMm: 510,
    weightG: 3500,
    fruit: "Citrouille",
    fruitEmoji: "🎃",
    babyDevelopment: "C'est la semaine prévue ! Le bébé est prêt à naître. Il pèse en moyenne 3,5 kg et mesure environ 51 cm.",
    momTips: "C'est la date prévue d'accouchement. Soyez patiente si bébé n'est pas encore là - c'est normal jusqu'à 42 semaines.",
    trimester: 3,
  },
  {
    week: 41,
    sizeMm: 515,
    weightG: 3600,
    fruit: "Pastèque",
    fruitEmoji: "🍉",
    babyDevelopment: "Le bébé continue de prendre du poids. Le placenta commence à vieillir. Le liquide amniotique peut diminuer légèrement.",
    momTips: "Votre médecin surveillera de près votre bébé. Un déclenchement peut être envisagé. Restez calme.",
    trimester: 3,
  },
  {
    week: 42,
    sizeMm: 520,
    weightG: 3700,
    fruit: "Pastèque géante",
    fruitEmoji: "🍉",
    babyDevelopment: "Le bébé est post-terme. Un déclenchement du travail sera probablement recommandé. Bébé est prêt !",
    momTips: "Vous êtes suivie de très près par l'équipe médicale. La naissance est imminente. Vous avez fait un travail incroyable !",
    trimester: 3,
  },
];

export function getWeekData(week: number): WeekData {
  const data = pregnancyData.find((d) => d.week === week);
  return data ?? pregnancyData[39]; // default to week 40
}

export function getCurrentWeek(dueDate: Date): number {
  const now = new Date();
  const diffMs = dueDate.getTime() - now.getTime();
  const diffDays = Math.ceil(diffMs / (1000 * 60 * 60 * 24));
  const weeksRemaining = Math.ceil(diffDays / 7);
  const currentWeek = 40 - weeksRemaining;
  return Math.max(1, Math.min(42, currentWeek));
}

export function getDaysRemaining(dueDate: Date): number {
  const now = new Date();
  const diffMs = dueDate.getTime() - now.getTime();
  return Math.max(0, Math.ceil(diffMs / (1000 * 60 * 60 * 24)));
}

export function getProgressPercent(dueDate: Date): number {
  const week = getCurrentWeek(dueDate);
  return Math.min(100, Math.round((week / 40) * 100));
}
