export interface Prenom {
  nom: string;
  genre: 'M' | 'F' | 'mixte';
  origine: string;
  signification: string;
  popularite: 1 | 2 | 3;
}

export const prenoms: Prenom[] = [
  // Français - Filles
  { nom: "Emma", genre: "F", origine: "Français", signification: "Entière, universelle", popularite: 3 },
  { nom: "Chloé", genre: "F", origine: "Français", signification: "Jeune pousse verte", popularite: 3 },
  { nom: "Léa", genre: "F", origine: "Hébreu", signification: "Lasse, fatiguée (mais aussi gaie)", popularite: 3 },
  { nom: "Manon", genre: "F", origine: "Français", signification: "Amour, grâce", popularite: 3 },
  { nom: "Inès", genre: "F", origine: "Espagnol", signification: "Pure, chaste", popularite: 3 },
  { nom: "Camille", genre: "mixte", origine: "Latin", signification: "Qui sert les dieux", popularite: 3 },
  { nom: "Jade", genre: "F", origine: "Espagnol", signification: "Pierre précieuse verte", popularite: 3 },
  { nom: "Lucie", genre: "F", origine: "Latin", signification: "Lumière", popularite: 2 },
  { nom: "Mathilde", genre: "F", origine: "Germanique", signification: "Force au combat", popularite: 2 },
  { nom: "Clara", genre: "F", origine: "Latin", signification: "Claire, brillante", popularite: 2 },
  { nom: "Alice", genre: "F", origine: "Germanique", signification: "Noble, de haute naissance", popularite: 3 },
  { nom: "Anaïs", genre: "F", origine: "Hébreu", signification: "Grâce divine", popularite: 2 },
  { nom: "Margot", genre: "F", origine: "Français", signification: "Perle", popularite: 2 },
  { nom: "Julie", genre: "F", origine: "Latin", signification: "Qui appartient à la famille Julia", popularite: 2 },
  { nom: "Laura", genre: "F", origine: "Latin", signification: "Laurier, victoire", popularite: 2 },
  { nom: "Pauline", genre: "F", origine: "Latin", signification: "Petite, humble", popularite: 2 },
  { nom: "Marie", genre: "F", origine: "Hébreu", signification: "Bien-aimée de Dieu", popularite: 2 },
  { nom: "Sophie", genre: "F", origine: "Grec", signification: "Sagesse", popularite: 2 },
  { nom: "Elisa", genre: "F", origine: "Hébreu", signification: "Mon Dieu est serment", popularite: 2 },
  { nom: "Valentine", genre: "F", origine: "Latin", signification: "Vigoureuse, forte", popularite: 2 },
  { nom: "Charlotte", genre: "F", origine: "Germanique", signification: "Femme libre", popularite: 3 },
  { nom: "Louise", genre: "F", origine: "Germanique", signification: "Guerrière illustre", popularite: 3 },
  { nom: "Juliette", genre: "F", origine: "Latin", signification: "Jeune, pleine de vitalité", popularite: 3 },
  { nom: "Zoé", genre: "F", origine: "Grec", signification: "Vie", popularite: 3 },
  { nom: "Léonie", genre: "F", origine: "Latin", signification: "Lionne courageuse", popularite: 2 },
  { nom: "Clémence", genre: "F", origine: "Latin", signification: "Douce, clémente", popularite: 2 },
  { nom: "Victoire", genre: "F", origine: "Latin", signification: "Victoire", popularite: 2 },
  { nom: "Céleste", genre: "F", origine: "Latin", signification: "Du ciel, divine", popularite: 1 },
  { nom: "Romane", genre: "F", origine: "Latin", signification: "De Rome", popularite: 2 },
  { nom: "Élise", genre: "F", origine: "Hébreu", signification: "Mon Dieu est serment", popularite: 2 },
  { nom: "Ambre", genre: "F", origine: "Arabe", signification: "Résine précieuse", popularite: 2 },
  { nom: "Noémie", genre: "F", origine: "Hébreu", signification: "Douce, agréable", popularite: 2 },
  { nom: "Océane", genre: "F", origine: "Grec", signification: "Océan, mer", popularite: 2 },
  { nom: "Maëlys", genre: "F", origine: "Breton", signification: "Princesse, chef", popularite: 2 },
  { nom: "Adèle", genre: "F", origine: "Germanique", signification: "Noble, de haute naissance", popularite: 2 },
  { nom: "Axelle", genre: "F", origine: "Hébreu", signification: "Mon père est la paix", popularite: 1 },
  { nom: "Béatrice", genre: "F", origine: "Latin", signification: "Celle qui rend heureux", popularite: 1 },
  { nom: "Constance", genre: "F", origine: "Latin", signification: "Constante, fidèle", popularite: 1 },
  { nom: "Diane", genre: "F", origine: "Latin", signification: "Divine, déesse de la chasse", popularite: 1 },
  { nom: "Élodie", genre: "F", origine: "Grec", signification: "Fleur des marais", popularite: 1 },
  { nom: "Floriane", genre: "F", origine: "Latin", signification: "Fleur, épanouie", popularite: 1 },
  { nom: "Gabrielle", genre: "F", origine: "Hébreu", signification: "Dieu est ma force", popularite: 2 },
  { nom: "Héloïse", genre: "F", origine: "Germanique", signification: "Saine, robuste", popularite: 2 },
  { nom: "Iris", genre: "F", origine: "Grec", signification: "Arc-en-ciel", popularite: 2 },
  { nom: "Jeanne", genre: "F", origine: "Hébreu", signification: "Dieu est bienveillant", popularite: 3 },
  { nom: "Lilou", genre: "F", origine: "Occitan", signification: "Lys, fleur", popularite: 2 },
  { nom: "Mélanie", genre: "F", origine: "Grec", signification: "Sombre, de teint brun", popularite: 2 },
  { nom: "Nathalie", genre: "F", origine: "Latin", signification: "Née à Noël", popularite: 1 },
  { nom: "Perrine", genre: "F", origine: "Latin", signification: "Pierre, roc", popularite: 1 },
  { nom: "Rosalie", genre: "F", origine: "Latin", signification: "Rose, fleur", popularite: 1 },
  { nom: "Sixtine", genre: "F", origine: "Latin", signification: "Sixième", popularite: 1 },
  { nom: "Tatiana", genre: "F", origine: "Latin", signification: "Fondatrice", popularite: 1 },
  { nom: "Agathe", genre: "F", origine: "Grec", signification: "Bonne, aimable", popularite: 2 },

  // Français - Garçons
  { nom: "Hugo", genre: "M", origine: "Germanique", signification: "Esprit, intelligence", popularite: 3 },
  { nom: "Louis", genre: "M", origine: "Germanique", signification: "Guerrier illustre", popularite: 3 },
  { nom: "Lucas", genre: "M", origine: "Latin", signification: "Lumière", popularite: 3 },
  { nom: "Nathan", genre: "M", origine: "Hébreu", signification: "Il a donné", popularite: 3 },
  { nom: "Tom", genre: "M", origine: "Hébreu", signification: "Jumeau", popularite: 2 },
  { nom: "Théo", genre: "M", origine: "Grec", signification: "Don de Dieu", popularite: 3 },
  { nom: "Mathis", genre: "M", origine: "Hébreu", signification: "Don de Dieu", popularite: 2 },
  { nom: "Jules", genre: "M", origine: "Latin", signification: "Aux cheveux bouclés, juvénile", popularite: 3 },
  { nom: "Antoine", genre: "M", origine: "Latin", signification: "Florissant, inestimable", popularite: 2 },
  { nom: "Clément", genre: "M", origine: "Latin", signification: "Doux, clément", popularite: 2 },
  { nom: "Baptiste", genre: "M", origine: "Grec", signification: "Celui qui baptise", popularite: 2 },
  { nom: "Nicolas", genre: "M", origine: "Grec", signification: "Victoire du peuple", popularite: 2 },
  { nom: "Pierre", genre: "M", origine: "Grec", signification: "Roc, pierre", popularite: 2 },
  { nom: "Paul", genre: "M", origine: "Latin", signification: "Petit, humble", popularite: 2 },
  { nom: "Victor", genre: "M", origine: "Latin", signification: "Victorieux", popularite: 2 },
  { nom: "Arthur", genre: "M", origine: "Celtique", signification: "Ours, noble", popularite: 3 },
  { nom: "Raphaël", genre: "M", origine: "Hébreu", signification: "Dieu guérit", popularite: 3 },
  { nom: "Gabriel", genre: "M", origine: "Hébreu", signification: "Dieu est ma force", popularite: 3 },
  { nom: "Maxime", genre: "M", origine: "Latin", signification: "Le plus grand", popularite: 2 },
  { nom: "Simon", genre: "M", origine: "Hébreu", signification: "Qui écoute", popularite: 2 },
  { nom: "Alexis", genre: "mixte", origine: "Grec", signification: "Qui protège", popularite: 2 },
  { nom: "Thomas", genre: "M", origine: "Hébreu", signification: "Jumeau", popularite: 3 },
  { nom: "Romain", genre: "M", origine: "Latin", signification: "Citoyen de Rome", popularite: 2 },
  { nom: "Tristan", genre: "M", origine: "Celtique", signification: "Tumulte, bruit", popularite: 2 },
  { nom: "Adrien", genre: "M", origine: "Latin", signification: "D'Hadria", popularite: 2 },
  { nom: "Florian", genre: "M", origine: "Latin", signification: "Fleur, épanoui", popularite: 1 },
  { nom: "Valentin", genre: "M", origine: "Latin", signification: "Vigoureux, fort", popularite: 2 },
  { nom: "Étienne", genre: "M", origine: "Grec", signification: "Couronné", popularite: 1 },
  { nom: "François", genre: "M", origine: "Latin", signification: "Franc, libre", popularite: 1 },
  { nom: "Guillaume", genre: "M", origine: "Germanique", signification: "Volonté de protection", popularite: 2 },
  { nom: "Henri", genre: "M", origine: "Germanique", signification: "Maître de la maison", popularite: 1 },
  { nom: "Julien", genre: "M", origine: "Latin", signification: "Juvénile, jeune", popularite: 2 },
  { nom: "Léon", genre: "M", origine: "Latin", signification: "Lion", popularite: 3 },
  { nom: "Marcel", genre: "M", origine: "Latin", signification: "Petit marteau", popularite: 1 },
  { nom: "Olivier", genre: "M", origine: "Latin", signification: "Olivier, arbre de paix", popularite: 1 },
  { nom: "Quentin", genre: "M", origine: "Latin", signification: "Cinquième", popularite: 2 },
  { nom: "Rémi", genre: "M", origine: "Latin", signification: "Rameur", popularite: 2 },
  { nom: "Sébastien", genre: "M", origine: "Grec", signification: "Vénérable, respecté", popularite: 1 },
  { nom: "Xavier", genre: "M", origine: "Basque", signification: "Maison neuve", popularite: 1 },
  { nom: "Yann", genre: "M", origine: "Breton", signification: "Dieu est bienveillant", popularite: 1 },

  // Anglais - Filles
  { nom: "Olivia", genre: "F", origine: "Anglais", signification: "Olivier, paix", popularite: 3 },
  { nom: "Emily", genre: "F", origine: "Anglais", signification: "Travailleuse, zélée", popularite: 3 },
  { nom: "Ava", genre: "F", origine: "Anglais", signification: "Comme un oiseau", popularite: 3 },
  { nom: "Sophia", genre: "F", origine: "Grec", signification: "Sagesse", popularite: 3 },
  { nom: "Isabella", genre: "F", origine: "Anglais", signification: "Mon Dieu est serment", popularite: 3 },
  { nom: "Mia", genre: "F", origine: "Scandinave", signification: "La mienne, chérie", popularite: 3 },
  { nom: "Abby", genre: "F", origine: "Hébreu", signification: "Joie du père", popularite: 1 },
  { nom: "Bella", genre: "F", origine: "Italien", signification: "Belle", popularite: 2 },
  { nom: "Chloe", genre: "F", origine: "Anglais", signification: "Floraison printanière", popularite: 2 },
  { nom: "Daisy", genre: "F", origine: "Anglais", signification: "Marguerite, fleur", popularite: 2 },
  { nom: "Ella", genre: "F", origine: "Anglais", signification: "Lumière, belle", popularite: 3 },
  { nom: "Fiona", genre: "F", origine: "Gaélique", signification: "Blanche, pure", popularite: 2 },
  { nom: "Grace", genre: "F", origine: "Anglais", signification: "Grâce divine", popularite: 2 },
  { nom: "Hannah", genre: "F", origine: "Hébreu", signification: "Grâce de Dieu", popularite: 2 },
  { nom: "Lily", genre: "F", origine: "Anglais", signification: "Lys, fleur de pureté", popularite: 3 },
  { nom: "Scarlett", genre: "F", origine: "Anglais", signification: "Écarlate, rouge vif", popularite: 2 },
  { nom: "Willow", genre: "F", origine: "Anglais", signification: "Saule, arbre souple", popularite: 2 },
  { nom: "Zara", genre: "F", origine: "Arabe/Hébreu", signification: "Fleur épanouie", popularite: 2 },

  // Anglais - Garçons
  { nom: "Liam", genre: "M", origine: "Anglais", signification: "Volonté de protection", popularite: 3 },
  { nom: "Noah", genre: "M", origine: "Hébreu", signification: "Repos, paix", popularite: 3 },
  { nom: "Oliver", genre: "M", origine: "Anglais", signification: "Olivier, paix", popularite: 3 },
  { nom: "Elijah", genre: "M", origine: "Hébreu", signification: "Mon Dieu est Yahvé", popularite: 2 },
  { nom: "James", genre: "M", origine: "Anglais", signification: "Qui supplante", popularite: 2 },
  { nom: "William", genre: "M", origine: "Anglais", signification: "Volonté de protection", popularite: 2 },
  { nom: "Benjamin", genre: "M", origine: "Hébreu", signification: "Fils de ma droite", popularite: 3 },
  { nom: "Lucas", genre: "M", origine: "Anglais", signification: "Lumière", popularite: 3 },
  { nom: "Henry", genre: "M", origine: "Anglais", signification: "Maître de la maison", popularite: 2 },
  { nom: "Alexander", genre: "M", origine: "Grec", signification: "Défenseur des hommes", popularite: 2 },
  { nom: "Mason", genre: "M", origine: "Anglais", signification: "Maçon", popularite: 2 },
  { nom: "Ethan", genre: "M", origine: "Hébreu", signification: "Solide, constant", popularite: 2 },
  { nom: "Jack", genre: "M", origine: "Anglais", signification: "Dieu est bienveillant", popularite: 2 },
  { nom: "Owen", genre: "M", origine: "Gallois", signification: "Jeune guerrier", popularite: 2 },
  { nom: "Charlie", genre: "mixte", origine: "Anglais", signification: "Homme libre", popularite: 2 },
  { nom: "Ryan", genre: "M", origine: "Irlandais", signification: "Petit roi", popularite: 2 },

  // Arabes - Filles
  { nom: "Yasmine", genre: "F", origine: "Arabe", signification: "Fleur de jasmin", popularite: 3 },
  { nom: "Fatima", genre: "F", origine: "Arabe", signification: "Celle qui sèvre", popularite: 2 },
  { nom: "Leila", genre: "F", origine: "Arabe", signification: "Nuit, nuit de beauté", popularite: 2 },
  { nom: "Sara", genre: "F", origine: "Hébreu/Arabe", signification: "Princesse", popularite: 3 },
  { nom: "Nadia", genre: "F", origine: "Arabe/Slave", signification: "Espoir, tendre", popularite: 2 },
  { nom: "Rania", genre: "F", origine: "Arabe", signification: "Regarder avec admiration", popularite: 2 },
  { nom: "Lina", genre: "F", origine: "Arabe", signification: "Tendre, douce", popularite: 3 },
  { nom: "Sanaa", genre: "F", origine: "Arabe", signification: "Brillance, beauté", popularite: 1 },
  { nom: "Samira", genre: "F", origine: "Arabe", signification: "Agréable compagnie nocturne", popularite: 1 },
  { nom: "Malak", genre: "F", origine: "Arabe", signification: "Ange", popularite: 2 },
  { nom: "Hajar", genre: "F", origine: "Arabe", signification: "Qui migre", popularite: 2 },
  { nom: "Imane", genre: "F", origine: "Arabe", signification: "Foi, croyance", popularite: 2 },
  { nom: "Kenza", genre: "F", origine: "Arabe", signification: "Trésor", popularite: 2 },
  { nom: "Meryem", genre: "F", origine: "Arabe", signification: "Aimée, désirée", popularite: 2 },
  { nom: "Nour", genre: "mixte", origine: "Arabe", signification: "Lumière", popularite: 3 },
  { nom: "Rima", genre: "F", origine: "Arabe", signification: "Gazelle blanche", popularite: 1 },
  { nom: "Sonia", genre: "F", origine: "Arabe/Slave", signification: "Sagesse", popularite: 2 },
  { nom: "Wafa", genre: "F", origine: "Arabe", signification: "Fidélité, loyauté", popularite: 1 },
  { nom: "Zineb", genre: "F", origine: "Arabe", signification: "Parure de son père", popularite: 2 },

  // Arabes - Garçons
  { nom: "Amine", genre: "M", origine: "Arabe", signification: "Fidèle, honnête", popularite: 3 },
  { nom: "Karim", genre: "M", origine: "Arabe", signification: "Généreux, noble", popularite: 2 },
  { nom: "Youssef", genre: "M", origine: "Arabe", signification: "Dieu augmente", popularite: 3 },
  { nom: "Adam", genre: "M", origine: "Hébreu/Arabe", signification: "Homme de la terre", popularite: 3 },
  { nom: "Mehdi", genre: "M", origine: "Arabe", signification: "Bien guidé", popularite: 2 },
  { nom: "Bilal", genre: "M", origine: "Arabe", signification: "Humidité, fraîcheur", popularite: 2 },
  { nom: "Rachid", genre: "M", origine: "Arabe", signification: "Bien guidé, sage", popularite: 2 },
  { nom: "Sami", genre: "M", origine: "Arabe", signification: "Élevé, sublime", popularite: 2 },
  { nom: "Tarik", genre: "M", origine: "Arabe", signification: "Celui qui frappe la porte de nuit", popularite: 1 },
  { nom: "Omar", genre: "M", origine: "Arabe", signification: "Vie longue, florissant", popularite: 2 },
  { nom: "Ilyas", genre: "M", origine: "Arabe", signification: "Mon Dieu est Yahvé", popularite: 2 },
  { nom: "Hamza", genre: "M", origine: "Arabe", signification: "Lion, fort", popularite: 2 },
  { nom: "Idriss", genre: "M", origine: "Arabe", signification: "Studieux, instruit", popularite: 1 },
  { nom: "Khalil", genre: "M", origine: "Arabe", signification: "Ami intime", popularite: 1 },
  { nom: "Malik", genre: "M", origine: "Arabe", signification: "Roi, maître", popularite: 2 },
  { nom: "Nassim", genre: "mixte", origine: "Arabe", signification: "Brise légère", popularite: 2 },
  { nom: "Oussama", genre: "M", origine: "Arabe", signification: "Lion", popularite: 1 },
  { nom: "Rayan", genre: "M", origine: "Arabe", signification: "Portes du paradis", popularite: 3 },

  // Hébreux
  { nom: "David", genre: "M", origine: "Hébreu", signification: "Bien-aimé", popularite: 2 },
  { nom: "Sarah", genre: "F", origine: "Hébreu", signification: "Princesse", popularite: 3 },
  { nom: "Samuel", genre: "M", origine: "Hébreu", signification: "Dieu a entendu", popularite: 2 },
  { nom: "Rebecca", genre: "F", origine: "Hébreu", signification: "Captivante", popularite: 1 },
  { nom: "Élie", genre: "M", origine: "Hébreu", signification: "Mon Dieu est Yahvé", popularite: 2 },
  { nom: "Rachel", genre: "F", origine: "Hébreu", signification: "Brebis", popularite: 2 },
  { nom: "Jonathan", genre: "M", origine: "Hébreu", signification: "Dieu a donné", popularite: 2 },
  { nom: "Miriam", genre: "F", origine: "Hébreu", signification: "Bien-aimée, mer amère", popularite: 1 },
  { nom: "Éden", genre: "mixte", origine: "Hébreu", signification: "Délice, paradis", popularite: 2 },
  { nom: "Elia", genre: "mixte", origine: "Hébreu", signification: "Mon Dieu est Yahvé", popularite: 2 },
  { nom: "Noam", genre: "mixte", origine: "Hébreu", signification: "Douceur, charme", popularite: 2 },
  { nom: "Shira", genre: "F", origine: "Hébreu", signification: "Chanson, poème", popularite: 1 },

  // Latins
  { nom: "Aurore", genre: "F", origine: "Latin", signification: "Aube, lumière du matin", popularite: 2 },
  { nom: "Maximus", genre: "M", origine: "Latin", signification: "Le plus grand", popularite: 1 },
  { nom: "Amélie", genre: "F", origine: "Latin", signification: "Travailleuse, active", popularite: 2 },
  { nom: "Augustin", genre: "M", origine: "Latin", signification: "Vénérable, majestueux", popularite: 2 },
  { nom: "Flore", genre: "F", origine: "Latin", signification: "Fleur, déesse des fleurs", popularite: 1 },
  { nom: "Félix", genre: "M", origine: "Latin", signification: "Heureux, chanceux", popularite: 2 },
  { nom: "Grâce", genre: "F", origine: "Latin", signification: "Grâce, faveur divine", popularite: 1 },
  { nom: "Maxence", genre: "mixte", origine: "Latin", signification: "Le plus grand", popularite: 2 },
  { nom: "Aurélien", genre: "M", origine: "Latin", signification: "D'or", popularite: 1 },
  { nom: "Claudia", genre: "F", origine: "Latin", signification: "Boiteuse", popularite: 1 },
  { nom: "Laurent", genre: "M", origine: "Latin", signification: "Couronné de laurier", popularite: 1 },
  { nom: "Véronique", genre: "F", origine: "Latin", signification: "Image vraie", popularite: 1 },

  // Scandinaves
  { nom: "Astrid", genre: "F", origine: "Scandinave", signification: "Force divine", popularite: 2 },
  { nom: "Erik", genre: "M", origine: "Scandinave", signification: "Toujours puissant", popularite: 2 },
  { nom: "Ingrid", genre: "F", origine: "Scandinave", signification: "Beauté d'Ing", popularite: 1 },
  { nom: "Lars", genre: "M", origine: "Scandinave", signification: "Couronné de laurier", popularite: 1 },
  { nom: "Sigrid", genre: "F", origine: "Scandinave", signification: "Belle victoire", popularite: 1 },
  { nom: "Sven", genre: "M", origine: "Scandinave", signification: "Jeune homme", popularite: 1 },
  { nom: "Freya", genre: "F", origine: "Scandinave", signification: "Dame noble, déesse de l'amour", popularite: 2 },
  { nom: "Björn", genre: "M", origine: "Scandinave", signification: "Ours", popularite: 1 },
  { nom: "Elsa", genre: "F", origine: "Scandinave", signification: "Dieu est serment", popularite: 3 },
  { nom: "Axel", genre: "M", origine: "Scandinave", signification: "Mon père est la paix", popularite: 2 },
  { nom: "Maja", genre: "F", origine: "Scandinave", signification: "Perle, mère", popularite: 2 },
  { nom: "Soren", genre: "M", origine: "Scandinave", signification: "Sévère", popularite: 1 },
  { nom: "Nora", genre: "F", origine: "Scandinave", signification: "Lumière, honneur", popularite: 3 },
  { nom: "Leif", genre: "M", origine: "Scandinave", signification: "Héritier, descendant", popularite: 1 },
  { nom: "Solveig", genre: "F", origine: "Scandinave", signification: "Chemin du soleil", popularite: 1 },
  { nom: "Magnus", genre: "M", origine: "Scandinave", signification: "Grand, puissant", popularite: 1 },

  // Italiens / Espagnols
  { nom: "Sofia", genre: "F", origine: "Italien", signification: "Sagesse", popularite: 3 },
  { nom: "Matteo", genre: "M", origine: "Italien", signification: "Don de Dieu", popularite: 3 },
  { nom: "Elena", genre: "F", origine: "Grec/Italien", signification: "Lumineuse, brillante", popularite: 2 },
  { nom: "Leonardo", genre: "M", origine: "Italien", signification: "Lion courageux", popularite: 2 },
  { nom: "Valentina", genre: "F", origine: "Latin", signification: "Forte, vigoureuse", popularite: 2 },
  { nom: "Marco", genre: "M", origine: "Latin", signification: "Dieu de la guerre", popularite: 2 },
  { nom: "Lucia", genre: "F", origine: "Latin", signification: "Lumière", popularite: 2 },
  { nom: "Carlos", genre: "M", origine: "Espagnol", signification: "Homme libre", popularite: 1 },
  { nom: "Isabella", genre: "F", origine: "Espagnol", signification: "Mon Dieu est serment", popularite: 3 },
  { nom: "Diego", genre: "M", origine: "Espagnol", signification: "Qui supplante", popularite: 2 },
  { nom: "Camila", genre: "F", origine: "Espagnol", signification: "Qui sert les dieux", popularite: 2 },

  // Prénoms mixtes / tendance
  { nom: "Alexia", genre: "F", origine: "Grec", signification: "Qui protège", popularite: 2 },
  { nom: "Célian", genre: "M", origine: "Latin", signification: "Du ciel", popularite: 1 },
  { nom: "Daphné", genre: "F", origine: "Grec", signification: "Laurier", popularite: 1 },
  { nom: "Emilio", genre: "M", origine: "Latin", signification: "Travailleur, zélé", popularite: 1 },
  { nom: "Faustine", genre: "F", origine: "Latin", signification: "Chanceuse, fortunée", popularite: 1 },
  { nom: "Gaston", genre: "M", origine: "Germanique", signification: "Hôte, étranger", popularite: 1 },
  { nom: "Honorine", genre: "F", origine: "Latin", signification: "Honorable", popularite: 1 },
  { nom: "Isidore", genre: "M", origine: "Grec", signification: "Don d'Isis", popularite: 1 },
  { nom: "Joséphine", genre: "F", origine: "Hébreu", signification: "Dieu augmente", popularite: 2 },
  { nom: "Kilian", genre: "M", origine: "Irlandais", signification: "Petit guerrier", popularite: 2 },
  { nom: "Laure", genre: "F", origine: "Latin", signification: "Laurier", popularite: 1 },
  { nom: "Mathéo", genre: "M", origine: "Hébreu", signification: "Don de Dieu", popularite: 2 },
  { nom: "Naomi", genre: "F", origine: "Hébreu", signification: "Mon délice", popularite: 2 },
  { nom: "Oriane", genre: "F", origine: "Latin", signification: "De l'orient, dorée", popularite: 1 },
  { nom: "Penelope", genre: "F", origine: "Grec", signification: "Tisserande fidèle", popularite: 1 },
  { nom: "Quinn", genre: "mixte", origine: "Irlandais", signification: "Sage, intelligence", popularite: 1 },
  { nom: "Rémy", genre: "M", origine: "Latin", signification: "Rameur", popularite: 2 },
  { nom: "Suzanne", genre: "F", origine: "Hébreu", signification: "Lys, fleur de pureté", popularite: 1 },
  { nom: "Thibault", genre: "M", origine: "Germanique", signification: "Peuple courageux", popularite: 1 },
  { nom: "Ulysse", genre: "M", origine: "Grec", signification: "Colère, irrité", popularite: 1 },
  { nom: "Viviane", genre: "F", origine: "Latin", signification: "Vivante, animée", popularite: 1 },
  { nom: "Wilda", genre: "F", origine: "Germanique", signification: "Sauvage, libre", popularite: 1 },
  { nom: "Ysée", genre: "F", origine: "Grec", signification: "Égale, semblable", popularite: 1 },
  { nom: "Zélie", genre: "F", origine: "Grec", signification: "Zèle, ardeur", popularite: 2 },
  { nom: "Archibald", genre: "M", origine: "Germanique", signification: "Noble, courageux", popularite: 1 },
  { nom: "Blanche", genre: "F", origine: "Germanique", signification: "Blanche, pure", popularite: 2 },
  { nom: "Cyprien", genre: "M", origine: "Latin", signification: "De Chypre", popularite: 1 },
  { nom: "Delphine", genre: "F", origine: "Latin", signification: "Dauphin, de Delphes", popularite: 1 },
  { nom: "Émilien", genre: "M", origine: "Latin", signification: "Travailleur", popularite: 1 },
  { nom: "Flavie", genre: "F", origine: "Latin", signification: "Blonde, dorée", popularite: 1 },
  { nom: "Gaspard", genre: "M", origine: "Persan", signification: "Gardien du trésor", popularite: 2 },
  { nom: "Honoré", genre: "M", origine: "Latin", signification: "Honorable, distingué", popularite: 1 },
  { nom: "Isaure", genre: "F", origine: "Grec", signification: "D'Isaurie", popularite: 1 },
  { nom: "Jérémie", genre: "M", origine: "Hébreu", signification: "Dieu élève", popularite: 2 },
  { nom: "Loup", genre: "M", origine: "Latin", signification: "Loup", popularite: 1 },
  { nom: "Milan", genre: "M", origine: "Slave", signification: "Gracieux, aimable", popularite: 2 },
  { nom: "Nils", genre: "M", origine: "Scandinave", signification: "Victoire du peuple", popularite: 1 },
  { nom: "Ophélie", genre: "F", origine: "Grec", signification: "Aide, secours", popularite: 2 },
  { nom: "Prune", genre: "F", origine: "Français", signification: "Fruit doux", popularite: 1 },
  { nom: "Roméo", genre: "M", origine: "Latin", signification: "Pèlerin de Rome", popularite: 1 },
  { nom: "Selena", genre: "F", origine: "Grec", signification: "Lune", popularite: 2 },
  { nom: "Timéo", genre: "M", origine: "Grec", signification: "Honoré de Dieu", popularite: 2 },
  { nom: "Lena", genre: "F", origine: "Grec", signification: "Lumineuse", popularite: 3 },
  { nom: "Maïa", genre: "F", origine: "Grec", signification: "Mère, nourricière", popularite: 2 },
  { nom: "Léa", genre: "F", origine: "Hébreu", signification: "Fatiguée, gaie", popularite: 3 },
];

export const origines = Array.from(new Set(prenoms.map(p => p.origine))).sort();
