export interface Prenom {
  nom: string;
  genre: 'M' | 'F' | 'mixte';
  origine: string;
  signification: string;
  popularite: 1 | 2 | 3;
}

export const prenoms: Prenom[] = [
  // Français populaires - Filles
  { nom: "Emma", genre: "F", origine: "Germanique", signification: "Entière, universelle", popularite: 3 },
  { nom: "Jade", genre: "F", origine: "Espagnol", signification: "Pierre précieuse verte", popularite: 3 },
  { nom: "Chloé", genre: "F", origine: "Grec", signification: "Jeune pousse verte", popularite: 3 },
  { nom: "Inès", genre: "F", origine: "Grec/Latin", signification: "Pure, chaste", popularite: 3 },
  { nom: "Léa", genre: "F", origine: "Hébreu", signification: "Fatiguée, délicate", popularite: 3 },
  { nom: "Manon", genre: "F", origine: "Hébreu", signification: "Dieu est avec nous", popularite: 3 },
  { nom: "Camille", genre: "F", origine: "Latin", signification: "Jeune fille de cérémonie", popularite: 3 },
  { nom: "Lucie", genre: "F", origine: "Latin", signification: "Lumière", popularite: 3 },
  { nom: "Zoé", genre: "F", origine: "Grec", signification: "Vie", popularite: 3 },
  { nom: "Clara", genre: "F", origine: "Latin", signification: "Claire, brillante", popularite: 3 },
  { nom: "Alice", genre: "F", origine: "Germanique", signification: "Noble, de noble nature", popularite: 3 },
  { nom: "Mathilde", genre: "F", origine: "Germanique", signification: "Force au combat", popularite: 3 },
  { nom: "Lola", genre: "F", origine: "Espagnol", signification: "Forme de Dolores, douleurs", popularite: 3 },
  { nom: "Louise", genre: "F", origine: "Germanique", signification: "Guerrière glorieuse", popularite: 3 },
  { nom: "Charlotte", genre: "F", origine: "Germanique", signification: "Femme libre", popularite: 3 },
  { nom: "Amélie", genre: "F", origine: "Germanique", signification: "Travailleuse, active", popularite: 3 },
  { nom: "Margot", genre: "F", origine: "Grec", signification: "Perle", popularite: 3 },
  { nom: "Valentine", genre: "F", origine: "Latin", signification: "Forte, valeur", popularite: 3 },
  { nom: "Pauline", genre: "F", origine: "Latin", signification: "Petite, humble", popularite: 3 },
  { nom: "Juliette", genre: "F", origine: "Latin", signification: "Jeune, juvénile", popularite: 3 },
  { nom: "Élise", genre: "F", origine: "Hébreu", signification: "Dieu est mon serment", popularite: 2 },
  { nom: "Anaïs", genre: "F", origine: "Hébreu/Grec", signification: "Grâce, faveur divine", popularite: 2 },
  { nom: "Clémence", genre: "F", origine: "Latin", signification: "Douce, clémente", popularite: 2 },
  { nom: "Coline", genre: "F", origine: "Grec", signification: "Victoire du peuple", popularite: 2 },
  { nom: "Océane", genre: "F", origine: "Grec", signification: "L'océan, la mer", popularite: 2 },
  { nom: "Noémie", genre: "F", origine: "Hébreu", signification: "Agréable, délicieuse", popularite: 2 },
  { nom: "Maëlys", genre: "F", origine: "Breton", signification: "Lumineuse, princesse", popularite: 2 },
  { nom: "Lena", genre: "F", origine: "Grec", signification: "Lumière, torche", popularite: 2 },
  { nom: "Romane", genre: "F", origine: "Latin", signification: "De Rome, romaine", popularite: 2 },
  { nom: "Capucine", genre: "F", origine: "Latin", signification: "Capucin, fleur", popularite: 2 },
  { nom: "Gaëlle", genre: "F", origine: "Breton", signification: "Générosité", popularite: 2 },
  { nom: "Laurie", genre: "F", origine: "Latin", signification: "Laurier, victoire", popularite: 2 },
  { nom: "Céline", genre: "F", origine: "Latin", signification: "Lune, ciel", popularite: 2 },
  { nom: "Marion", genre: "F", origine: "Hébreu", signification: "Étoile de la mer", popularite: 2 },
  { nom: "Héloïse", genre: "F", origine: "Germanique", signification: "Santé, large", popularite: 1 },
  { nom: "Constance", genre: "F", origine: "Latin", signification: "Constante, stable", popularite: 1 },
  { nom: "Victoire", genre: "F", origine: "Latin", signification: "Victoire", popularite: 1 },
  { nom: "Apolline", genre: "F", origine: "Grec", signification: "Apollon, soleil", popularite: 1 },
  { nom: "Blanche", genre: "F", origine: "Germanique", signification: "Blanc, pur", popularite: 1 },
  { nom: "Céleste", genre: "F", origine: "Latin", signification: "Céleste, du ciel", popularite: 1 },
  { nom: "Flavie", genre: "F", origine: "Latin", signification: "Blonde, dorée", popularite: 1 },
  { nom: "Albane", genre: "F", origine: "Latin", signification: "Blanche, de l'aube", popularite: 1 },
  { nom: "Philomène", genre: "F", origine: "Grec", signification: "Qui aime le chant", popularite: 1 },

  // Français populaires - Garçons
  { nom: "Louis", genre: "M", origine: "Germanique", signification: "Guerrier glorieux", popularite: 3 },
  { nom: "Gabriel", genre: "M", origine: "Hébreu", signification: "Homme de Dieu", popularite: 3 },
  { nom: "Hugo", genre: "M", origine: "Germanique", signification: "Esprit, intelligence", popularite: 3 },
  { nom: "Arthur", genre: "M", origine: "Celtique", signification: "Ours", popularite: 3 },
  { nom: "Raphaël", genre: "M", origine: "Hébreu", signification: "Dieu guérit", popularite: 3 },
  { nom: "Lucas", genre: "M", origine: "Grec/Latin", signification: "Lumière", popularite: 3 },
  { nom: "Mathis", genre: "M", origine: "Hébreu", signification: "Don de Dieu", popularite: 3 },
  { nom: "Théo", genre: "M", origine: "Grec", signification: "Don de Dieu", popularite: 3 },
  { nom: "Ethan", genre: "M", origine: "Hébreu", signification: "Fort, solide", popularite: 3 },
  { nom: "Noah", genre: "M", origine: "Hébreu", signification: "Repos, consolation", popularite: 3 },
  { nom: "Tom", genre: "M", origine: "Hébreu", signification: "Jumeau", popularite: 3 },
  { nom: "Léo", genre: "M", origine: "Latin", signification: "Lion", popularite: 3 },
  { nom: "Maxime", genre: "M", origine: "Latin", signification: "Le plus grand", popularite: 3 },
  { nom: "Antoine", genre: "M", origine: "Latin", signification: "Inestimable, précieux", popularite: 3 },
  { nom: "Clément", genre: "M", origine: "Latin", signification: "Doux, clément", popularite: 3 },
  { nom: "Nicolas", genre: "M", origine: "Grec", signification: "Victoire du peuple", popularite: 3 },
  { nom: "Pierre", genre: "M", origine: "Grec", signification: "Pierre, roc", popularite: 2 },
  { nom: "Alexandre", genre: "M", origine: "Grec", signification: "Défenseur des hommes", popularite: 3 },
  { nom: "Axel", genre: "M", origine: "Nordique", signification: "Père de la paix", popularite: 2 },
  { nom: "Baptiste", genre: "M", origine: "Grec", signification: "Celui qui baptise", popularite: 2 },
  { nom: "Benjamin", genre: "M", origine: "Hébreu", signification: "Fils du côté droit", popularite: 2 },
  { nom: "Édouard", genre: "M", origine: "Anglais", signification: "Gardien de la richesse", popularite: 2 },
  { nom: "Florian", genre: "M", origine: "Latin", signification: "Fleur, fleuri", popularite: 2 },
  { nom: "Gauthier", genre: "M", origine: "Germanique", signification: "Armée de guerre", popularite: 1 },
  { nom: "Guillaume", genre: "M", origine: "Germanique", signification: "Volonté de protéger", popularite: 2 },
  { nom: "Julien", genre: "M", origine: "Latin", signification: "Descendant de Jules", popularite: 2 },
  { nom: "Kevin", genre: "M", origine: "Irlandais", signification: "Beau, bien né", popularite: 2 },
  { nom: "Laurent", genre: "M", origine: "Latin", signification: "Couronné de laurier", popularite: 1 },
  { nom: "Martin", genre: "M", origine: "Latin", signification: "Guerrier de Mars", popularite: 2 },
  { nom: "Olivier", genre: "M", origine: "Latin", signification: "Olivier, paix", popularite: 2 },
  { nom: "Paul", genre: "M", origine: "Latin", signification: "Petit, humble", popularite: 2 },
  { nom: "Quentin", genre: "M", origine: "Latin", signification: "Le cinquième", popularite: 2 },
  { nom: "Romain", genre: "M", origine: "Latin", signification: "Romain, de Rome", popularite: 2 },
  { nom: "Simon", genre: "M", origine: "Hébreu", signification: "Celui qui entend", popularite: 2 },
  { nom: "Victor", genre: "M", origine: "Latin", signification: "Vainqueur", popularite: 2 },
  { nom: "Valentin", genre: "M", origine: "Latin", signification: "Fort, vigoureux", popularite: 2 },
  { nom: "Xavier", genre: "M", origine: "Basque", signification: "Maison neuve", popularite: 1 },
  { nom: "Yann", genre: "M", origine: "Breton/Hébreu", signification: "Dieu est gracieux", popularite: 1 },
  { nom: "Zacharie", genre: "M", origine: "Hébreu", signification: "Dieu se souvient", popularite: 1 },
  { nom: "Côme", genre: "M", origine: "Grec", signification: "Ordre, beauté", popularite: 1 },
  { nom: "Félicien", genre: "M", origine: "Latin", signification: "Heureux, fortuné", popularite: 1 },

  // Prénoms arabes - Filles
  { nom: "Yasmine", genre: "F", origine: "Arabe", signification: "Fleur de jasmin", popularite: 3 },
  { nom: "Fatima", genre: "F", origine: "Arabe", signification: "Celle qui sevra son enfant", popularite: 3 },
  { nom: "Nour", genre: "F", origine: "Arabe", signification: "Lumière", popularite: 3 },
  { nom: "Sara", genre: "F", origine: "Hébreu/Arabe", signification: "Princesse", popularite: 3 },
  { nom: "Amina", genre: "F", origine: "Arabe", signification: "Fidèle, honnête", popularite: 3 },
  { nom: "Leila", genre: "F", origine: "Arabe", signification: "Nuit, nuit de beauté", popularite: 3 },
  { nom: "Meriem", genre: "F", origine: "Arabe/Hébreu", signification: "Étoile de la mer", popularite: 3 },
  { nom: "Rania", genre: "F", origine: "Arabe", signification: "Contemplative, admirable", popularite: 2 },
  { nom: "Hafsa", genre: "F", origine: "Arabe", signification: "Lionne", popularite: 2 },
  { nom: "Khadija", genre: "F", origine: "Arabe", signification: "Née avant terme, précieuse", popularite: 2 },
  { nom: "Hana", genre: "F", origine: "Arabe", signification: "Bonheur, félicité", popularite: 2 },
  { nom: "Salma", genre: "F", origine: "Arabe", signification: "Paix, sûreté", popularite: 2 },
  { nom: "Nadia", genre: "F", origine: "Arabe/Slave", signification: "Espoir", popularite: 2 },
  { nom: "Dounia", genre: "F", origine: "Arabe", signification: "Le monde terrestre", popularite: 2 },
  { nom: "Samia", genre: "F", origine: "Arabe", signification: "Élevée, noble", popularite: 2 },

  // Prénoms arabes - Garçons
  { nom: "Amine", genre: "M", origine: "Arabe", signification: "Fidèle, honnête", popularite: 3 },
  { nom: "Youssef", genre: "M", origine: "Arabe/Hébreu", signification: "Dieu ajoutera", popularite: 3 },
  { nom: "Rayan", genre: "M", origine: "Arabe", signification: "Porte du paradis, irrigué", popularite: 3 },
  { nom: "Mohamed", genre: "M", origine: "Arabe", signification: "Digne de louanges", popularite: 3 },
  { nom: "Adam", genre: "M", origine: "Hébreu/Arabe", signification: "Fait de terre", popularite: 3 },
  { nom: "Karim", genre: "M", origine: "Arabe", signification: "Généreux, noble", popularite: 3 },
  { nom: "Sami", genre: "M", origine: "Arabe", signification: "Élevé, sublime", popularite: 2 },
  { nom: "Omar", genre: "M", origine: "Arabe", signification: "Longue vie, prospère", popularite: 2 },
  { nom: "Zakaria", genre: "M", origine: "Arabe/Hébreu", signification: "Dieu se souvient", popularite: 2 },
  { nom: "Idriss", genre: "M", origine: "Arabe", signification: "Studieux, instruit", popularite: 2 },
  { nom: "Hamza", genre: "M", origine: "Arabe", signification: "Lion, fort", popularite: 2 },
  { nom: "Bilal", genre: "M", origine: "Arabe", signification: "Fraîcheur de l'eau", popularite: 2 },
  { nom: "Hassan", genre: "M", origine: "Arabe", signification: "Beau, bon", popularite: 2 },
  { nom: "Sofiane", genre: "M", origine: "Arabe", signification: "Rapide, énergique", popularite: 2 },
  { nom: "Walid", genre: "M", origine: "Arabe", signification: "Nouveau-né, enfant", popularite: 2 },
  { nom: "Tariq", genre: "M", origine: "Arabe", signification: "Celui qui frappe à la porte la nuit", popularite: 1 },

  // Prénoms anglais/américains - Filles
  { nom: "Olivia", genre: "F", origine: "Latin/Anglais", signification: "Olivier, paix", popularite: 3 },
  { nom: "Sophia", genre: "F", origine: "Grec", signification: "Sagesse", popularite: 3 },
  { nom: "Lily", genre: "F", origine: "Anglais", signification: "Fleur de lys", popularite: 3 },
  { nom: "Emily", genre: "F", origine: "Latin", signification: "Rivale, laborieuse", popularite: 3 },
  { nom: "Mia", genre: "F", origine: "Scandinave/Hébreu", signification: "Chérie, la mienne", popularite: 3 },
  { nom: "Ava", genre: "F", origine: "Latin/Hébreu", signification: "Vie, oiseau", popularite: 3 },
  { nom: "Isabella", genre: "F", origine: "Hébreu/Espagnol", signification: "Consacrée à Dieu", popularite: 3 },
  { nom: "Aria", genre: "F", origine: "Italien", signification: "Air, mélodie", popularite: 2 },
  { nom: "Grace", genre: "F", origine: "Latin", signification: "Grâce, élégance", popularite: 2 },
  { nom: "Stella", genre: "F", origine: "Latin", signification: "Étoile", popularite: 2 },
  { nom: "Chloe", genre: "F", origine: "Grec", signification: "Jeune pousse", popularite: 2 },
  { nom: "Penelope", genre: "F", origine: "Grec", signification: "Tisserande", popularite: 2 },
  { nom: "Scarlett", genre: "F", origine: "Anglais", signification: "Rouge écarlate", popularite: 2 },

  // Prénoms anglais/américains - Garçons
  { nom: "Liam", genre: "M", origine: "Irlandais", signification: "Volonté de protection", popularite: 3 },
  { nom: "Ethan", genre: "M", origine: "Hébreu", signification: "Fort, solide", popularite: 3 },
  { nom: "Oliver", genre: "M", origine: "Latin", signification: "Olivier, paix", popularite: 3 },
  { nom: "Jack", genre: "M", origine: "Anglais/Hébreu", signification: "Dieu est gracieux", popularite: 3 },
  { nom: "Elijah", genre: "M", origine: "Hébreu", signification: "Mon Dieu est Yahvé", popularite: 2 },
  { nom: "James", genre: "M", origine: "Hébreu", signification: "Supplanteur", popularite: 2 },
  { nom: "Henry", genre: "M", origine: "Germanique", signification: "Maître du foyer", popularite: 2 },
  { nom: "Mason", genre: "M", origine: "Anglais", signification: "Maçon, constructeur", popularite: 2 },
  { nom: "Sebastian", genre: "M", origine: "Grec", signification: "De Sébaste, vénérable", popularite: 2 },
  { nom: "Aiden", genre: "M", origine: "Irlandais", signification: "Feu, ardeur", popularite: 2 },

  // Prénoms hébreux/bibliques - Filles
  { nom: "Sarah", genre: "F", origine: "Hébreu", signification: "Princesse", popularite: 3 },
  { nom: "Rebecca", genre: "F", origine: "Hébreu", signification: "Captivante, liée", popularite: 2 },
  { nom: "Rachel", genre: "F", origine: "Hébreu", signification: "Brebis", popularite: 2 },
  { nom: "Hannah", genre: "F", origine: "Hébreu", signification: "Grâce, faveur", popularite: 2 },
  { nom: "Ruth", genre: "F", origine: "Hébreu", signification: "Amie, compagne", popularite: 1 },
  { nom: "Miriam", genre: "F", origine: "Hébreu", signification: "Aimée de Dieu", popularite: 1 },
  { nom: "Esther", genre: "F", origine: "Hébreu/Persan", signification: "Étoile", popularite: 2 },
  { nom: "Naomi", genre: "F", origine: "Hébreu", signification: "Agréable", popularite: 2 },
  { nom: "Déborah", genre: "F", origine: "Hébreu", signification: "Abeille", popularite: 1 },
  { nom: "Léah", genre: "F", origine: "Hébreu", signification: "Fatiguée, vache sauvage", popularite: 1 },

  // Prénoms hébreux/bibliques - Garçons
  { nom: "Aaron", genre: "M", origine: "Hébreu", signification: "Montagne, élevé", popularite: 2 },
  { nom: "Nathan", genre: "M", origine: "Hébreu", signification: "Dieu a donné", popularite: 3 },
  { nom: "Elias", genre: "M", origine: "Hébreu/Grec", signification: "Yahvé est mon Dieu", popularite: 2 },
  { nom: "Samuel", genre: "M", origine: "Hébreu", signification: "Dieu a entendu", popularite: 2 },
  { nom: "Isaac", genre: "M", origine: "Hébreu", signification: "Il rira", popularite: 2 },
  { nom: "Eli", genre: "M", origine: "Hébreu", signification: "Élevé, ascension", popularite: 2 },
  { nom: "Jonah", genre: "M", origine: "Hébreu", signification: "Colombe", popularite: 1 },
  { nom: "Caleb", genre: "M", origine: "Hébreu", signification: "Fidèle comme un chien", popularite: 2 },
  { nom: "Micah", genre: "M", origine: "Hébreu", signification: "Qui est semblable à Dieu?", popularite: 1 },
  { nom: "Ezra", genre: "M", origine: "Hébreu", signification: "Aide", popularite: 1 },

  // Prénoms italiens - Filles
  { nom: "Sofia", genre: "F", origine: "Grec/Italien", signification: "Sagesse", popularite: 3 },
  { nom: "Aurora", genre: "F", origine: "Latin/Italien", signification: "Aurore, aube", popularite: 3 },
  { nom: "Giulia", genre: "F", origine: "Latin/Italien", signification: "Juvénile", popularite: 2 },
  { nom: "Valentina", genre: "F", origine: "Latin/Italien", signification: "Forte, valeur", popularite: 2 },
  { nom: "Chiara", genre: "F", origine: "Latin/Italien", signification: "Claire, lumineuse", popularite: 2 },
  { nom: "Bianca", genre: "F", origine: "Germanique/Italien", signification: "Blanche, pure", popularite: 2 },
  { nom: "Eleonora", genre: "F", origine: "Provençal/Italien", signification: "Rayonnante", popularite: 1 },
  { nom: "Serena", genre: "F", origine: "Latin/Italien", signification: "Sereine, calme", popularite: 2 },

  // Prénoms italiens - Garçons
  { nom: "Lorenzo", genre: "M", origine: "Latin/Italien", signification: "Couronné de laurier", popularite: 2 },
  { nom: "Leonardo", genre: "M", origine: "Germanique/Italien", signification: "Lion audacieux", popularite: 2 },
  { nom: "Marco", genre: "M", origine: "Latin/Italien", signification: "Consacré à Mars", popularite: 2 },
  { nom: "Matteo", genre: "M", origine: "Hébreu/Italien", signification: "Don de Dieu", popularite: 2 },
  { nom: "Luca", genre: "M", origine: "Latin/Italien", signification: "Lumière", popularite: 3 },
  { nom: "Giovanni", genre: "M", origine: "Hébreu/Italien", signification: "Dieu est gracieux", popularite: 1 },
  { nom: "Enzo", genre: "M", origine: "Germanique/Italien", signification: "Maître du foyer", popularite: 2 },

  // Prénoms scandinaves - Filles
  { nom: "Luna", genre: "F", origine: "Latin/Scandinave", signification: "Lune", popularite: 3 },
  { nom: "Freya", genre: "F", origine: "Nordique", signification: "Dame, déesse de l'amour", popularite: 3 },
  { nom: "Astrid", genre: "F", origine: "Nordique", signification: "Force divine", popularite: 2 },
  { nom: "Sigrid", genre: "F", origine: "Nordique", signification: "Belle victoire", popularite: 1 },
  { nom: "Ingrid", genre: "F", origine: "Nordique", signification: "Cavalier d'Ing", popularite: 1 },
  { nom: "Liv", genre: "F", origine: "Nordique", signification: "Protection, vie", popularite: 1 },
  { nom: "Maja", genre: "F", origine: "Nordique", signification: "Perle, grande", popularite: 2 },
  { nom: "Elsa", genre: "F", origine: "Hébreu/Nordique", signification: "Mon Dieu est serment", popularite: 2 },
  { nom: "Britta", genre: "F", origine: "Nordique", signification: "Force, puissance", popularite: 1 },

  // Prénoms scandinaves - Garçons
  { nom: "Erik", genre: "M", origine: "Nordique", signification: "Roi éternel", popularite: 2 },
  { nom: "Björn", genre: "M", origine: "Nordique", signification: "Ours", popularite: 1 },
  { nom: "Magnus", genre: "M", origine: "Latin/Nordique", signification: "Grand", popularite: 1 },
  { nom: "Leif", genre: "M", origine: "Nordique", signification: "Héritier, successeur", popularite: 1 },
  { nom: "Sven", genre: "M", origine: "Nordique", signification: "Jeune homme", popularite: 1 },
  { nom: "Lars", genre: "M", origine: "Nordique/Latin", signification: "Couronné de laurier", popularite: 1 },
  { nom: "Mikael", genre: "M", origine: "Hébreu/Nordique", signification: "Qui est comme Dieu?", popularite: 2 },
  { nom: "Gunnar", genre: "M", origine: "Nordique", signification: "Guerrier", popularite: 1 },
  { nom: "Sigurd", genre: "M", origine: "Nordique", signification: "Gardien de la victoire", popularite: 1 },

  // Mixtes / Nature / Modernes
  { nom: "Eden", genre: "mixte", origine: "Hébreu", signification: "Délice, paradis", popularite: 3 },
  { nom: "Sasha", genre: "mixte", origine: "Grec/Russe", signification: "Défenseur de l'homme", popularite: 3 },
  { nom: "Charlie", genre: "mixte", origine: "Germanique", signification: "Homme libre", popularite: 3 },
  { nom: "Camille", genre: "mixte", origine: "Latin", signification: "Jeune servante", popularite: 2 },
  { nom: "Morgan", genre: "mixte", origine: "Gallois", signification: "Bord de mer", popularite: 2 },
  { nom: "Alex", genre: "mixte", origine: "Grec", signification: "Défenseur", popularite: 2 },
  { nom: "Robin", genre: "mixte", origine: "Germanique", signification: "Brillant de gloire", popularite: 2 },
  { nom: "Noa", genre: "mixte", origine: "Hébreu", signification: "Mouvement, repos", popularite: 3 },
  { nom: "Lune", genre: "F", origine: "Latin/Français", signification: "La lune", popularite: 2 },
  { nom: "Rivière", genre: "F", origine: "Français/Nature", signification: "Cours d'eau", popularite: 1 },
  { nom: "Jasper", genre: "M", origine: "Persan", signification: "Trésor", popularite: 1 },
  { nom: "Célian", genre: "M", origine: "Latin", signification: "Du ciel", popularite: 2 },
  { nom: "Soleil", genre: "F", origine: "Latin/Français", signification: "Le soleil", popularite: 1 },
  { nom: "Aurore", genre: "F", origine: "Latin", signification: "Aube, aurore", popularite: 2 },
  { nom: "Phoenix", genre: "mixte", origine: "Grec", signification: "Oiseau renaissant", popularite: 1 },
  { nom: "Sky", genre: "mixte", origine: "Anglais", signification: "Ciel", popularite: 1 },
  { nom: "River", genre: "mixte", origine: "Anglais", signification: "Rivière", popularite: 1 },
  { nom: "Sage", genre: "mixte", origine: "Latin/Anglais", signification: "Sage, plante aromatique", popularite: 1 },

  // Prénoms espagnols/latino - Filles
  { nom: "María", genre: "F", origine: "Hébreu/Espagnol", signification: "Étoile de la mer", popularite: 3 },
  { nom: "Carmen", genre: "F", origine: "Latin/Espagnol", signification: "Chanson, jardin", popularite: 2 },
  { nom: "Elena", genre: "F", origine: "Grec/Espagnol", signification: "Lumière, torche", popularite: 3 },
  { nom: "Lucia", genre: "F", origine: "Latin/Espagnol", signification: "Lumière", popularite: 3 },
  { nom: "Isabela", genre: "F", origine: "Hébreu/Espagnol", signification: "Consacrée à Dieu", popularite: 2 },
  { nom: "Nadia", genre: "F", origine: "Slave/Arabe", signification: "Espoir, tendresse", popularite: 2 },
  { nom: "Alba", genre: "F", origine: "Latin/Espagnol", signification: "Blanche, aube", popularite: 2 },
  { nom: "Valentina", genre: "F", origine: "Latin/Espagnol", signification: "Forte, vigoureuse", popularite: 2 },

  // Prénoms espagnols/latino - Garçons
  { nom: "Carlos", genre: "M", origine: "Germanique/Espagnol", signification: "Homme libre", popularite: 2 },
  { nom: "Diego", genre: "M", origine: "Hébreu/Espagnol", signification: "Supplanteur", popularite: 2 },
  { nom: "Alejandro", genre: "M", origine: "Grec/Espagnol", signification: "Défenseur des hommes", popularite: 2 },
  { nom: "Juan", genre: "M", origine: "Hébreu/Espagnol", signification: "Dieu est gracieux", popularite: 2 },
  { nom: "Mateo", genre: "M", origine: "Hébreu/Espagnol", signification: "Don de Dieu", popularite: 3 },
  { nom: "Santiago", genre: "M", origine: "Hébreu/Espagnol", signification: "Saint Jacques", popularite: 2 },
  { nom: "Leo", genre: "M", origine: "Latin/Espagnol", signification: "Lion", popularite: 3 },

  // Prénoms grecs/mythologiques
  { nom: "Athéna", genre: "F", origine: "Grec", signification: "Déesse de la sagesse", popularite: 1 },
  { nom: "Héra", genre: "F", origine: "Grec", signification: "Reine des dieux", popularite: 1 },
  { nom: "Iris", genre: "F", origine: "Grec", signification: "Arc-en-ciel, messagère", popularite: 2 },
  { nom: "Pénélope", genre: "F", origine: "Grec", signification: "Tisserande fidèle", popularite: 2 },
  { nom: "Andromède", genre: "F", origine: "Grec", signification: "Penseuse d'hommes", popularite: 1 },
  { nom: "Daphné", genre: "F", origine: "Grec", signification: "Laurier", popularite: 2 },
  { nom: "Perséphone", genre: "F", origine: "Grec", signification: "Porteuse de destruction", popularite: 1 },
  { nom: "Ajax", genre: "M", origine: "Grec", signification: "Aigle de la terre", popularite: 1 },
  { nom: "Achille", genre: "M", origine: "Grec", signification: "Lèvres fines", popularite: 1 },
  { nom: "Orion", genre: "M", origine: "Grec", signification: "Chasseur", popularite: 1 },
  { nom: "Théodore", genre: "M", origine: "Grec", signification: "Don de Dieu", popularite: 2 },
  { nom: "Alexis", genre: "mixte", origine: "Grec", signification: "Défenseur", popularite: 2 },

  // Prénoms d'origine africaine
  { nom: "Aminata", genre: "F", origine: "Africain/Arabe", signification: "Fidèle, honnête", popularite: 2 },
  { nom: "Fatoumata", genre: "F", origine: "Africain/Arabe", signification: "Celle qui sevra", popularite: 2 },
  { nom: "Aïssatou", genre: "F", origine: "Africain/Hébreu", signification: "Vie", popularite: 2 },
  { nom: "Mariama", genre: "F", origine: "Africain/Arabe", signification: "Vénérée", popularite: 2 },
  { nom: "Khady", genre: "F", origine: "Africain", signification: "Bonne nature", popularite: 1 },
  { nom: "Ibrahima", genre: "M", origine: "Africain/Hébreu", signification: "Père des nations", popularite: 2 },
  { nom: "Moussa", genre: "M", origine: "Africain/Hébreu", signification: "Tiré des eaux", popularite: 2 },
  { nom: "Cheikh", genre: "M", origine: "Africain/Arabe", signification: "Chef, sage", popularite: 2 },
  { nom: "Mamadou", genre: "M", origine: "Africain/Arabe", signification: "Digne de louanges", popularite: 2 },
  { nom: "Abdou", genre: "M", origine: "Africain/Arabe", signification: "Serviteur", popularite: 2 },

  // Prénoms d'Europe de l'Est / Slaves
  { nom: "Natasha", genre: "F", origine: "Latin/Russe", signification: "Née à Noël", popularite: 2 },
  { nom: "Olga", genre: "F", origine: "Nordique/Russe", signification: "Sainte, bénie", popularite: 1 },
  { nom: "Katia", genre: "F", origine: "Grec/Russe", signification: "Pure, chaste", popularite: 2 },
  { nom: "Irina", genre: "F", origine: "Grec/Russe", signification: "Paix", popularite: 1 },
  { nom: "Tatiana", genre: "F", origine: "Latin/Russe", signification: "De la famille Tatiana", popularite: 1 },
  { nom: "Dmitri", genre: "M", origine: "Grec/Russe", signification: "Dévoué à Déméter", popularite: 1 },
  { nom: "Ivan", genre: "M", origine: "Hébreu/Russe", signification: "Dieu est gracieux", popularite: 2 },
  { nom: "Alexei", genre: "M", origine: "Grec/Russe", signification: "Défenseur", popularite: 1 },
  { nom: "Nikolai", genre: "M", origine: "Grec/Russe", signification: "Victoire du peuple", popularite: 1 },
  { nom: "Boris", genre: "M", origine: "Slave", signification: "Combattant de gloire", popularite: 1 },

  // Prénoms japonais/asiatiques
  { nom: "Sakura", genre: "F", origine: "Japonais", signification: "Fleur de cerisier", popularite: 2 },
  { nom: "Yuki", genre: "F", origine: "Japonais", signification: "Neige, bonheur", popularite: 1 },
  { nom: "Aiko", genre: "F", origine: "Japonais", signification: "Enfant de l'amour", popularite: 1 },
  { nom: "Hana", genre: "F", origine: "Japonais/Arabe", signification: "Fleur, bonheur", popularite: 2 },
  { nom: "Kenji", genre: "M", origine: "Japonais", signification: "Fils fort", popularite: 1 },
  { nom: "Riku", genre: "M", origine: "Japonais", signification: "Terre, sol", popularite: 1 },

  // Prénoms celtiques/bretons
  { nom: "Gwenaëlle", genre: "F", origine: "Breton", signification: "Blanche et généreuse", popularite: 2 },
  { nom: "Enora", genre: "F", origine: "Breton", signification: "Honneur", popularite: 2 },
  { nom: "Maïwenn", genre: "F", origine: "Breton", signification: "Belle Marie", popularite: 1 },
  { nom: "Rozenn", genre: "F", origine: "Breton", signification: "Rose", popularite: 1 },
  { nom: "Tugdual", genre: "M", origine: "Breton", signification: "Valeur du peuple", popularite: 1 },
  { nom: "Erwann", genre: "M", origine: "Breton", signification: "If, archer", popularite: 1 },
  { nom: "Loïg", genre: "M", origine: "Breton", signification: "Guerrier glorieux", popularite: 1 },
  { nom: "Malo", genre: "M", origine: "Breton", signification: "Prince, chef", popularite: 2 },

  // Prénoms modernes / tendance
  { nom: "Léonie", genre: "F", origine: "Latin", signification: "Lionne", popularite: 3 },
  { nom: "Maëlle", genre: "F", origine: "Breton", signification: "Princesse, chef", popularite: 2 },
  { nom: "Nora", genre: "F", origine: "Hébreu/Irlandais", signification: "Honneur, lumière", popularite: 3 },
  { nom: "Alexia", genre: "F", origine: "Grec", signification: "Protectrice", popularite: 2 },
  { nom: "Tina", genre: "F", origine: "Latin", signification: "Rivière, consacrée", popularite: 2 },
  { nom: "Léana", genre: "F", origine: "Français", signification: "Lumière agréable", popularite: 2 },
  { nom: "Eléonore", genre: "F", origine: "Provençal", signification: "Lumière de pitié", popularite: 2 },
  { nom: "Mathéo", genre: "M", origine: "Hébreu/Français", signification: "Don de Dieu", popularite: 3 },
  { nom: "Milo", genre: "M", origine: "Germanique/Latin", signification: "Doux, gracieux", popularite: 2 },
  { nom: "Owen", genre: "M", origine: "Gallois", signification: "Né noble", popularite: 2 },
  { nom: "Nolan", genre: "M", origine: "Irlandais", signification: "Champion, notable", popularite: 3 },
  { nom: "Ryan", genre: "M", origine: "Irlandais", signification: "Petit roi", popularite: 3 },
  { nom: "Evan", genre: "M", origine: "Gallois/Hébreu", signification: "Dieu est gracieux", popularite: 2 },
  { nom: "Ilan", genre: "M", origine: "Hébreu", signification: "Arbre", popularite: 2 },
  { nom: "Lenny", genre: "M", origine: "Germanique", signification: "Lion audacieux", popularite: 2 },
  { nom: "Maël", genre: "M", origine: "Breton", signification: "Prince, chef", popularite: 3 },
  { nom: "Timéo", genre: "M", origine: "Hébreu/Grec", signification: "Honoré par Dieu", popularite: 3 },
  { nom: "Yoann", genre: "M", origine: "Hébreu", signification: "Dieu est gracieux", popularite: 2 },
  { nom: "Kilian", genre: "M", origine: "Irlandais", signification: "Petit belliqueux", popularite: 2 },
  { nom: "Sacha", genre: "mixte", origine: "Grec/Russe", signification: "Défenseur de l'homme", popularite: 3 },
  { nom: "Tao", genre: "M", origine: "Chinois", signification: "La voie, chemin", popularite: 1 },
  { nom: "Zéphyr", genre: "M", origine: "Grec", signification: "Vent d'ouest", popularite: 1 },
  { nom: "Céleste", genre: "F", origine: "Latin", signification: "Du ciel, céleste", popularite: 2 },
  { nom: "Ondine", genre: "F", origine: "Latin", signification: "Petite vague", popularite: 1 },
  { nom: "Sienna", genre: "F", origine: "Italien", signification: "De Sienne", popularite: 2 },
  { nom: "Camille", genre: "M", origine: "Latin", signification: "Serviteur du temple", popularite: 1 },
  { nom: "Lys", genre: "F", origine: "Français", signification: "Fleur de lys", popularite: 1 },
  { nom: "Marin", genre: "M", origine: "Latin", signification: "De la mer", popularite: 2 },
  { nom: "Marine", genre: "F", origine: "Latin", signification: "De la mer", popularite: 2 },
  { nom: "Swann", genre: "mixte", origine: "Anglais", signification: "Cygne", popularite: 1 },
  { nom: "Jade", genre: "mixte", origine: "Espagnol", signification: "Pierre précieuse verte", popularite: 2 },
  { nom: "Nino", genre: "mixte", origine: "Géorgien/Espagnol", signification: "Jeune", popularite: 2 },
];
